---
ID: "7931267d-e754-496e-9dcc-dc85127d8efc"
Parent: "27f6aa64-10a7-4215-a6f4-516e5ffecf33"
Template: "27f6aa64-10a7-4215-a6f4-516e5ffecf33"
Path: /sitecore/templates/Feature/NOV Com/Modules/Social Channels/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181023T185249Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e2260a73-caf8-4b8c-b2ff-79e8f463875c"
    - ID: "8fa80c09-c998-475a-a4f6-2a131a48f48f"
      Hint: backgroundColor
      Value: white
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181023T185619Z
