---
ID: "707d6b9c-6b57-4681-b4ae-78b779aa4aad"
Parent: "aa99e7cc-b90e-4ee1-9881-287a2bbc8283"
Template: "d227ab0e-fd44-4ae0-878a-189949913d0b"
Path: /sitecore/content/nov/nov/Home/About/Our Business Units/Fluid Motion Solutions/Applications
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{C4ACEA35-73C2-4347-B325-2FC6FCDAAB8F}"
          s:ds="{BF742318-9587-4996-B1D2-BD5A765B4FD3}" />
        <r
          uid="{E655A92B-3794-4099-AF60-076BAFA33189}"
          s:ds="{E787FC1F-5F29-46CB-BAFD-3A6341C06C88}" />
        <r
          uid="{0D97EC48-A616-4503-81F3-8B0A22142C87}"
          s:ds="{A95E9F5D-32E0-40A4-8930-2B3BF333D005}" />
        <r
          uid="{1FD9ED8E-765E-4D75-AEB7-9C5643309FB1}"
          s:ds="{4188AA21-C983-4A27-81E9-001C5FA52D7B}" />
        <r
          uid="{C3E128BD-C527-476C-B850-4FF98996AE1F}"
          s:ds="{DEE4D5DD-691D-4995-A7E9-F8B8282974D7}" />
        <r
          uid="{9E4C6427-3865-4F4C-AF91-EFDF6A58DA77}"
          s:ds="{5AA8B3E2-14DC-4300-8D56-89B0DFA16FEC}" />
        <r
          uid="{ACAD23C8-9219-4D65-B38A-4537A73C4FE0}"
          s:ds="{92F98F4F-45CE-4932-8387-314C19D14A09}" />
        <r
          uid="{FB4C5C8E-DF5F-4300-950E-536065A8707B}"
          s:ds="{0DB3C01D-E8FC-4A17-99EF-AB463A348D32}" />
        <r
          uid="{2849CE03-88F2-4FBC-BAE4-0D1B29D7AEAA}"
          s:ds="{9AE29E02-E47F-4668-ADB4-08A0EB3A0A8E}" />
        <r
          uid="{B5407315-4598-49BA-A716-8895E8E1539E}"
          s:ds="{0ECB67B1-6D6E-4F02-9B42-C975029E4AD5}" />
        <r
          uid="{35F5B041-CCEA-40B8-948D-6DE09851A28E}"
          s:ds="{73F86E06-4A2C-4954-822C-AE2068BFECDD}" />
        <r
          uid="{99B4E79C-EEB8-49BC-8779-24C4AD0CF113}"
          s:ds="{7E3C03BA-FD59-4217-8B64-C18A14CB86A8}" />
        <r
          uid="{CDF8E396-F69A-48ED-A6DB-B665BD98B242}"
          s:ds="{E7BA960A-D4B7-4C7A-B0F7-D37D76C82A05}" />
      </d>
    </r>
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "01fd8c23-1b98-4e4b-9f2d-ecf3eb8aad68"
      Hint: businessUnits
      Value: "{424899CB-AF39-4DD1-9B7A-A18B0152D8EC}"
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{BA077E75-780B-4654-A220-10E63520C582}">
              <p:d />
            </r>
            <r
              uid="{83C96A38-D18A-4E35-9D8D-71F869B259F3}">
              <p:d />
            </r>
            <r
              uid="{C4ACEA35-73C2-4347-B325-2FC6FCDAAB8F}">
              <p:d />
            </r>
            <r
              uid="{012939C1-AA07-4752-B9B6-DC78094BD917}"
              p:before="*"
              s:ds=""
              s:id="{13EC6ADB-6326-43B6-8A85-0D8510F63F5B}"
              s:par=""
              s:ph="/main/text-only-hero-slide-{11F71874-8ABE-4F08-AD7C-39E6DECB985C}-0" />
            <r
              uid="{11F71874-8ABE-4F08-AD7C-39E6DECB985C}"
              p:after="r[@uid='{012939C1-AA07-4752-B9B6-DC78094BD917}']"
              s:id="{BD41E061-3601-46AF-AC01-7B0617E0836B}"
              s:ph="main" />
            <r
              uid="{B9603571-3DC6-4B28-BAED-7E2265E2078C}"
              p:after="r[@uid='{11F71874-8ABE-4F08-AD7C-39E6DECB985C}']"
              s:ds="{A46FA5AF-874E-48A6-8A22-7FE5A2FA183C}"
              s:id="{BA41A7D9-9B6F-4E1B-A8AD-9F1C5714660A}"
              s:ph="main" />
            <r
              uid="{E655A92B-3794-4099-AF60-076BAFA33189}">
              <p:d />
            </r>
            <r
              uid="{0D97EC48-A616-4503-81F3-8B0A22142C87}">
              <p:d />
            </r>
            <r
              uid="{1FD9ED8E-765E-4D75-AEB7-9C5643309FB1}">
              <p:d />
            </r>
            <r
              uid="{C3E128BD-C527-476C-B850-4FF98996AE1F}">
              <p:d />
            </r>
            <r
              uid="{9E4C6427-3865-4F4C-AF91-EFDF6A58DA77}">
              <p:d />
            </r>
            <r
              uid="{ACAD23C8-9219-4D65-B38A-4537A73C4FE0}">
              <p:d />
            </r>
            <r
              uid="{FB4C5C8E-DF5F-4300-950E-536065A8707B}">
              <p:d />
            </r>
            <r
              uid="{2849CE03-88F2-4FBC-BAE4-0D1B29D7AEAA}">
              <p:d />
            </r>
            <r
              uid="{B5407315-4598-49BA-A716-8895E8E1539E}">
              <p:d />
            </r>
            <r
              uid="{35F5B041-CCEA-40B8-948D-6DE09851A28E}">
              <p:d />
            </r>
            <r
              uid="{99B4E79C-EEB8-49BC-8779-24C4AD0CF113}">
              <p:d />
            </r>
            <r
              uid="{3ADDDF2A-6C4B-4473-ACB2-EADC8ABD6475}">
              <p:d />
            </r>
            <r
              uid="{8036035A-E577-44BC-A961-631ADBC08C0F}">
              <p:d />
            </r>
            <r
              uid="{AC9772AA-4069-4AB9-B2D2-02A9491C13F2}"
              p:after="r[@uid='{CDF8E396-F69A-48ED-A6DB-B665BD98B242}']"
              s:ds="{074D538A-A019-45B5-A201-6959CA84853C}"
              s:id="{404FE8DE-C601-4E14-8D3D-32F27B41D06D}"
              s:ph="main" />
            <r
              uid="{458F2AFF-7C50-47BF-AA73-A7346A7F262C}"
              p:after="*[1=2]"
              s:ds="{2314EC90-88F6-46C6-B7D8-E9E59E1D3876}"
              s:id="{95886CBA-BBC9-48E5-9C7B-97B40C8F9599}"
              s:par="Use Button for Link"
              s:ph="main" />
          </d>
        </r>
    - ID: "1e6decbd-039c-43cc-b439-0a198f868334"
      Hint: Featured Story Headline
      Value: 
    - ID: "21d62cf8-1209-47b9-a117-2bb93b891dad"
      Hint: Subheading
      Value: <p>Applications include water and wastewater, flue gas desulfurization, corn wet milling, oil and gas, ethanol, pulp and paper, polymer, chemical, fermentation, mineral processing, general, biotechnology</p>
    - ID: "230a15ec-92fd-4a68-954b-9689bcba0862"
      Hint: Headline
      Value: "Applications - Mixing Technologies"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220112T231217Z
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: "Applications - Mixing Technologies"
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{40251B7D-FBE3-4A0E-8947-D4B4FE8CD782}"
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: "Applications - Mixing Technologies"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "646de4d6-b128-4a3e-8c68-f789869a811b"
      Hint: businessSegments
      Value: "{ABA9E56C-0FCE-464D-8E09-DB375CDF20D8}"
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: "Applications - Mixing Technologies"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "85d2ec66-8aaf-431f-8bf7-bee7d87b89ad"
    - ID: "a1343418-5a51-40de-9488-0efaa22e2042"
      Hint: contentTag
      Value: "{97803E00-415E-418E-BD59-EC82DC5F73D8}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "c57e3a44-44b4-496a-9509-dfe938d498d9"
      Hint: Meta Description
      Value: Applications include water and wastewater, flue gas desulfurization, corn wet milling, oil and gas, ethanol, pulp and paper, polymer, chemical, fermentation, mineral processing, general, biotechnology
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220113T025551Z
