---
ID: "5b9c351f-c04c-460a-a207-75b72827a736"
Parent: "32d0f361-950a-40e9-b12c-54e938a490dd"
Template: "07c63710-4422-42b9-adb7-67b4bad63607"
Path: /sitecore/content/nov/nov/Data/Modules/Miscellaneous/Rig Systems Supplier Application Portal/Rig Supplier application portal D5 Article Text
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "0f10eefb-f9da-4b41-83a0-87900c4e25ed"
      Hint: body
      Value: |
        <p>The applications a supplier has access to will depend on the specific facility they are working with. If you are unsure which link to select, please reach out to your NOV representative for more information.</p>
        <p><strong><a rel="noopener noreferrer" href="https://iprsone.nov.com/" target="_blank">iSupplier</a><br />
        </strong>Used by Rig Systems to coordinate purchasing activities with vendors (RFQs, POs, Invoicing, etc.).</p>
        <p><strong><a rel="noopener noreferrer" href="https://gvi.nov.com/" target="_blank">Global Vendor Interface (GVI)</a><br />
        </strong>Used by Rig Aftermarket to coordinate purchasing activities with vendors (RFQs, POs, Invoicing, etc.).</p>
        <p><strong><a rel="noopener noreferrer" href="https://rigportal.nov.com/Bookshelf/" target="_blank">Bookshelf</a><br />
        </strong>Used by Rig Systems and Aftermarket for sharing documentation with external parties.</p>
        <p><strong><a href="https://rightnov.nov.com/">RightNOV</a><br />
        </strong>Used by Rig Systems for vendors to report progress and issues relating to orders.</p>
        <p>&nbsp;</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190506T171649Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kaileyshelton
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kaileyshelton
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "87ecc81e-fbd2-46a6-a8ff-16ebaf0d283b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kaileyshelton
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190506T175750Z
  - Version: 2
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "0f10eefb-f9da-4b41-83a0-87900c4e25ed"
      Hint: body
      Value: |
        <p>The applications a supplier has access to will depend on the specific facility they are working with. If you are unsure which link to select, please reach out to your NOV representative for more information.</p>
        <p><strong><a rel="noopener noreferrer" href="https://iprsone.nov.com/" target="_blank">iSupplier</a><br />
        </strong>Used by Rig Technologies to coordinate purchasing activities with vendors (RFQs, POs, Invoicing, etc.).</p>
        <p><strong><a rel="noopener noreferrer" href="https://gvi.nov.com/" target="_blank">Global Vendor Interface (GVI)</a><br />
        </strong>Used by Rig Aftermarket to coordinate purchasing activities with vendors (RFQs, POs, Invoicing, etc.).</p>
        <p><strong><a rel="noopener noreferrer" href="https://rigportal.nov.com/Bookshelf/" target="_blank">Bookshelf</a><br />
        </strong>Used by Rig Technologies&nbsp;and Aftermarket for sharing documentation with external parties.</p>
        <p><strong><a href="https://rightnov.nov.com/">RightNOV</a><br />
        </strong>Used by Rig Technologies&nbsp;for vendors to report progress and issues relating to orders.</p>
        <p>&nbsp;</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191119T155155Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{40251B7D-FBE3-4A0E-8947-D4B4FE8CD782}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kaileyshelton
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kaileyshelton
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1a11a2a5-a0b5-4b54-a627-4c83bf99b47a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kaileyshelton
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20191119T155155Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20191119T155248Z
