---
ID: "cb44f162-eb39-469d-bb4f-27c2d0e3f09d"
Parent: "7a274c62-3cac-4fb4-95ef-cea08fc11f65"
Template: "7a274c62-3cac-4fb4-95ef-cea08fc11f65"
Path: /sitecore/templates/Feature/NOV Com/Modules/Product/Brand Capability Filtered List/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190520T150053Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "6ceb6ae3-0f4d-4c43-8ab2-bb3df44ee2fe"
      Hint: capabilitiesHelpText
      Value: "What capabilities can we help you find?"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4b8161a4-f79d-4f2b-abcc-bf32e2c1a9cd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190520T150127Z
    - ID: "ef529711-91df-4d40-8222-44e71985a929"
      Hint: brandsHelpText
      Value: "What brands can we help you find?"
