---
ID: "acb83ea1-ea35-45da-82ed-895c27a7837b"
Parent: "5835dd1d-6338-41b9-9f25-0a3270a9669c"
Template: "814c1dbb-b118-4511-ba2b-7288ed3d490b"
Path: /sitecore/system/Modules/Layout Service/Rendering Contents Resolvers/Custom Contents Resolvers/ProductTabs Content Resolver
SharedFields:
- ID: "de218ede-a9ad-4b04-86c5-9ff593ccf39d"
  Hint: Type
  Value: XmCloudnov.ContentsResolver.ProductTabsContentResolver,XmCloudnov
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230726T111803Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rangre@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rangre@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b82e5cf5-6ec5-4704-8643-6a87124a888d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rangre@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230824T143825Z
