---
ID: "f98ed59e-43a5-4968-b09c-2c9b37319409"
Parent: "5b27436c-a823-4a17-9a33-b08cbabc9cf5"
Template: "2a8117d9-ebd1-430b-abd4-1d33b1fee79c"
Path: /sitecore/content/nov/nov/Data/Modules/Products/CAPS/Process and Flow Technologies/Environmental Services/Environmental Services E5 Document List
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200918T182107Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{40251B7D-FBE3-4A0E-8947-D4B4FE8CD782}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8de063c0-74ca-4853-ac66-bb0d069b3692"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200918T182203Z
    - ID: "e4424681-e459-4738-a286-2240e08da75e"
      Hint: assets
      Value: |
        {159BCD9F-B466-4818-86C7-F8B0FA37AB0E}
        {D9644210-A5B9-4B46-A14C-91CC62263F0D}
