---
ID: "f6cf34a7-71b7-4795-9c55-d6b2f33d9f19"
Parent: "62562871-289f-4899-a6e4-d54e5f09f3bd"
Template: "62562871-289f-4899-a6e4-d54e5f09f3bd"
Path: /sitecore/templates/Feature/NOV Com/Modules/Search Modules/Search/__Standard Values
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170227T201542Z
    - ID: "4021e39b-36db-4812-9b88-d0cfd90d6769"
      Hint: popularSearchTerms
      Value: "Popular search terms:"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "220c5b61-f80a-4d6f-81d7-ba198abc84ac"
    - ID: "ad728314-7963-4484-bd52-bcb08e1e32cb"
      Hint: searchTerms
      Value: Term 1|Term 2|Term 3|Term 4
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181112T200248Z
