---
ID: "ea1f5e9a-bc06-45e4-a122-f2ab7dbdb007"
Parent: "28957a18-084b-4d4a-8e5a-106ef5677283"
Template: "07c63710-4422-42b9-adb7-67b4bad63607"
Path: /sitecore/content/nov/nov/Data/Modules/About/News/NOVs Chainsaw cutter configuration enables drilling performance improvements in the Permian/NOVs Chainsaw cutter configuration_D5 Article Text
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "0f10eefb-f9da-4b41-83a0-87900c4e25ed"
      Hint: body
      Value: |
        <p>By using Tektonic bits with cutters in the Chainsaw configuration, we're helping our customers achieve faster, more effective drilling. Each bit features an application-specific geometry tailored to formation challenges. This, combined with continuous engineering progress and exceptional field support, is changing the way our customers in the Permian perceive us. In <a href="~/link.aspx?_id=28D1EFA6724B4285B8587EDCC388C8E7&amp;_z=z">the latest issue</a>&nbsp;of Oilfield Technology, we discuss several case histories in which the Tektonic bits with ION cutters in Chainsaw configuration helped customers save money and beat ROP records.</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190621T153345Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\joannazhu
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\joannazhu
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "95523f4f-247a-46ae-a369-b80431265aa9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\joannazhu
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190621T154249Z
  - Version: 2
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "0f10eefb-f9da-4b41-83a0-87900c4e25ed"
      Hint: body
      Value: |
        <p>The innovative new Chainsaw&trade; cutter configuration unites our ION&trade; 3D cutters with full round cutters on the Tektonic&trade; drill bit to provide the shearing and fracturing cutting actions necessary to cut through shale and interbedded formations. Additionally, the cutters' polished surface reduces cuttings friction at the cutter face.</p>
        <p>By using Tektonic bits with cutters in the Chainsaw configuration, we're helping our customers achieve faster, more effective drilling. Each bit features an application-specific geometry tailored to formation challenges. This, combined with continuous engineering progress and exceptional field support, is changing the way our customers in the Permian perceive us. In <a href="~/link.aspx?_id=28D1EFA6724B4285B8587EDCC388C8E7&amp;_z=z">the latest issue</a>&nbsp;of Oilfield Technology, we discuss several case histories in which the Tektonic bits with ION cutters in Chainsaw configuration helped customers save money and beat ROP records.</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190621T193308Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\joannazhu
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\joannazhu
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b54121b6-a30f-4921-9143-d48089faf8f8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\joannazhu
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20190621T193308Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190621T193336Z
  - Version: 3
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "0f10eefb-f9da-4b41-83a0-87900c4e25ed"
      Hint: body
      Value: |
        <p>The innovative new Chainsaw&trade; cutter configuration unites our <a href="~/link.aspx?_id=7DC78F4DCBE74CBF87148F38DC5EB0B7&amp;_z=z">ION&trade; 3D cutters</a>&nbsp;with full round cutters on the <a href="~/link.aspx?_id=121C7FF19B0B4B1F9BAB38AE7F688C8C&amp;_z=z">Tektonic&trade; drill bit</a>&nbsp;to provide the shearing and fracturing cutting actions necessary to cut through shale and interbedded formations. Additionally, the cutters&rsquo; polished surface reduces cuttings friction at the cutter face.</p>
        <p>By using Tektonic bits with cutters in the Chainsaw configuration, we&rsquo;re helping our customers achieve faster, more effective drilling. Each bit features an application-specific geometry tailored to formation challenges. This, combined with continuous engineering progress and exceptional field support, is changing the way our customers in the Permian perceive us. In the <a href="~/link.aspx?_id=28D1EFA6724B4285B8587EDCC388C8E7&amp;_z=z">latest issue of <em>Oilfield Technology</em></a>, we discuss several case histories in which the Tektonic bits with ION cutters in Chainsaw configuration helped customers save money and beat ROP records.</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191111T232445Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\joannazhu
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\heatherbaxter
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4b630dcd-f0dd-4996-962e-68ca4d67b304"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\heatherbaxter
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20191111T232445Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20191111T232646Z
