---
ID: "cd42eabb-0d73-46a8-b286-c3a495dd0a2d"
Parent: "f9341431-8c0c-406f-8a02-3ffc0f0785cd"
Template: "f9341431-8c0c-406f-8a02-3ffc0f0785cd"
Path: /sitecore/templates/Feature/NOV Shared/Field Sections/Cropped Image Fields/Required/Image 480x1080 Required/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190121T182656Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5ce45e1e-5672-4ef5-9aef-3680aeb92c21"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190121T182656Z
