---
ID: "93554288-56e5-4994-b656-7a54a5e46e46"
Parent: "de3bb47c-38c2-46aa-a031-680a30f241b2"
Template: "5030864f-eb96-4da7-a417-e5a0108c59f8"
Path: /sitecore/content/nov/nov/Data/Modules/Products/WBT/Grant Prideco/Grant Prideco Double Shoulder Connections/GPDS and EIS Connections J6 Product Table Standard EIS Configurations for S135 Grade Drill Pipe
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200803T164901Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "89e0d08a-ef09-4651-9d48-1e619efc4cb2"
      Hint: table
      Value: |
        <table>
        <tbody>
        <tr>
        <td>
        Connection
        </td>
        <td>
        Pipe OD (in.)
        </td>
        <td>
        Nominal weight (lb/ft)
        </td>
        <td>
        Tool joint OD &times; ID (in.)
        </td>
        <td>
        Maximum MUT (ft-lb)
        </td>
        </tr>
        <tr>
        <td>
        NC 38 EIS
        </td>
        <td>
        3.500
        </td>
        <td>
        13.30
        </td>
        <td>
        5 x 2.438
        </td>
        <td>
        20,500
        </td>
        </tr>
        <tr>
        <td>
        NC 38 EIS
        </td>
        <td>
        3.500
        </td>
        <td>
        15.50
        </td>
        <td>
        5 x 2.438
        </td>
        <td>
        20,500
        </td>
        </tr>
        <tr>
        <td>
        NC 40 EIS
        </td>
        <td>
        4.000
        </td>
        <td>
        14.00
        </td>
        <td>
        5.250 &times; 2.563
        </td>
        <td>
        25,600
        </td>
        </tr>
        <tr>
        <td>
        NC 40 EIS
        </td>
        <td>
        4.000
        </td>
        <td>
        15.70
        </td>
        <td>
        5.250 &times; 2.563
        </td>
        <td>
        25,600
        </td>
        </tr>
        <tr>
        <td>
        NC 46 EIS
        </td>
        <td>
        4.500
        </td>
        <td>
        16.60
        </td>
        <td>
        6.000 &times; 3.000
        </td>
        <td>
        37,100
        </td>
        </tr>
        <tr>
        <td>
        NC 46 EIS
        </td>
        <td>
        4.500
        </td>
        <td>
        20.00
        </td>
        <td>
        6.000 &times; 3.000
        </td>
        <td>
        37,100
        </td>
        </tr>
        <tr>
        <td>
        NC 50 EIS
        </td>
        <td>
        5.000
        </td>
        <td>
        19.50
        </td>
        <td>
        6.625 &times; 3.250
        </td>
        <td>
        49,800
        </td>
        </tr>
        <tr>
        <td>
        NC 50 EIS
        </td>
        <td>
        5.000
        </td>
        <td>
        25.60
        </td>
        <td>
        6.625 &times; 3.250
        </td>
        <td>
        49,800
        </td>
        </tr>
        <tr>
        <td>
        5&frac12; FH EIS
        </td>
        <td>
        5.500
        </td>
        <td>
        21.90
        </td>
        <td>
        7.000 &times; 4.000
        </td>
        <td>
        50,700
        </td>
        </tr>
        <tr>
        <td>
        5&frac12; FH EIS
        </td>
        <td>
        5.500
        </td>
        <td>
        24.70
        </td>
        <td>
        7.000 &times; 4.000
        </td>
        <td>
        50,700
        </td>
        </tr>
        <tr>
        <td>
        5&frac12; FH EIS
        </td>
        <td>
        5.875
        </td>
        <td>
        23.40
        </td>
        <td>
        7.125 &times; 3.750
        </td>
        <td>
        60,600
        </td>
        </tr>
        <tr>
        <td>
        5&frac12; FH EIS
        </td>
        <td>
        5.875
        </td>
        <td>
        26.30
        </td>
        <td>
        7.125 &times; 3.750
        </td>
        <td>
        60,600
        </td>
        </tr>
        <tr>
        <td>
        6⅝ FH EIS
        </td>
        <td>
        6.625
        </td>
        <td>
        27.70
        </td>
        <td>
        8.125 &times; 4.875
        </td>
        <td>
        73,000
        </td>
        </tr>
        </tbody>
        </table>
        
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fe5c962c-3cfe-4460-9eb3-361dd05d7f6b"
    - ID: "915a3100-b6af-4b83-a168-471e1b3e74be"
      Hint: headline
      Value: "Standard EIS Configurations for S135-Grade Drill Pipe"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200806T223202Z
