---
ID: "dd2acd7a-e385-49f3-addb-fd019cc6baac"
Parent: "114fceda-549b-436b-b83e-b3fd82030738"
Template: "c0aa2bad-85b9-47e4-a236-901c3115fb87"
Path: /sitecore/content/nov/nov/Data/Modules/Products/WBT/Directional Drilling Technologies/Tolteq Hellfire MWD Configuration/Tolteq Hellfire MWD Configuration J5 Features List
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200827T195932Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8cc243c4-50ef-417c-b3b9-2ae01fec3b3c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "c3afee16-1dbc-4a49-8037-9d03d0d7d62e"
      Hint: description
      Value: |
        <p>Built on our highly successful Tolteq&trade; measurement-while-drilling (MWD) platform, the Tolteq Hellfire MWD configuration was specifically designed for the harsh, vibration-prone, and high-temperature conditions typical of North America wellbores. With a name to match its aggressive performance in harsh conditions, our Hellfire MWD system delivers advanced, continuous measurements supported by cutting-edge telemetry speed and consistency in an extremely reliable and cost-effective package.</p>
        <p>Hellfire MWD tools are available as a ready-to-deploy kit, combining the Tolteq NXT top-mount pulser, the new NXT directional module, SureMate&trade; centralizers, and the NXT GUIDE decoder. The Hellfire system leverages the latest top-mount pulser technology, which is engineered to perform in high-vibration environments while delivering exceptional pulse consistency and reliability even in extended-reach lateral applications. At 4 bits per second, we offer one of the fastest and most reliable data rates on the market, which is automatically decoded by the Hellfire&rsquo;s ultra-intuitive and remote-operations-enabled surface system.</p>
        <p>The Hellfire MWD configuration includes real-time pressure-while-drilling measurements, enabling access to advanced drilling optimization capability on every run. In addition, the Hellfire system can be configured to meet a wide variety of applications, including azimuthal gamma modules for more demanding reservoir navigation requirements.</p>
        <p>With a reliability-driven design philosophy and continued development leveraging NOV&rsquo;s world-class R&amp;D facilities, directional drillers can be assured that Tolteq MWD products will remain the leading independently manufactured MWD solution in the market. All Tolteq tools are fully designed and manufactured in-house by NOV experts using the latest manufacturing techniques and design standards to avoid compatibility and interface issues.</p>
        <p>For more information on the Tolteq Hellfire MWD Configuration, please contact Cary Eddy at <a href="mailto:MWD@nov.com">MWD@nov.com</a>, or fill out the form below.</p>
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200828T170100Z
