---
ID: "2d17ce26-1077-48a0-aef7-1787154210aa"
Parent: "76af14e3-bc24-479c-9121-5f77858d52d8"
Template: "76af14e3-bc24-479c-9121-5f77858d52d8"
Path: /sitecore/templates/Project/nov/NOV Com/Modules/Search Modules/Search Stats/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181103T231843Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6d0e3c22-fae4-48e3-8e67-414b013ff4e0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181103T231843Z
