---
ID: "18870756-d346-4634-abe9-077821c87fc8"
Parent: "0f7128b2-170a-4feb-b135-797c21c4ce17"
Template: "c0aa2bad-85b9-47e4-a236-901c3115fb87"
Path: /sitecore/content/nov/nov/Data/Modules/Products/CAPS/Completion Tools/Production Packers and Accessories/Production packers and accessories J5 Features List
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200723T204704Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kaileyshelton
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kaileyshelton
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "62259bf6-66c3-49d7-baee-84495ac7b973"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kaileyshelton
    - ID: "c3afee16-1dbc-4a49-8037-9d03d0d7d62e"
      Hint: description
      Value: |
        <p>Critical to your upper completion systems
        Production packers and their accessories are the cornerstones to most upper completion designs by providing a barrier to protect the casing and diverting flow into the tubing string. Our production packers include both retrievable and permanent type tools and have a full range of deployment options, including mechanical set, hydraulic set, and e-line set versions.
        </p>
        <p>We manufacture a full range of packers for most casing and tubing sizes and a broad range of applications, including thermal and high pressure, high temperature (HPHT) wells. We manufacture this equipment in accordance with industry standards for packers and their accessories.
        </p>
        <p><b>Our product offerings
        </b></p>
        <ul>
            <li>Mechanical packers
            </li>
            <li>Hydraulic packers
            </li>
            <li>Permanent packers
            </li>
            <li>Retrievable seal bore packers
            </li>
            <li>Seal bore packer accessories
            </li>
            <li>Completion accessories</li>
        </ul>
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200814T131339Z
