---
ID: "a9bebed3-4e05-48b8-8c0d-7b3d5b629314"
Parent: "d02f35f4-977c-4221-a979-6eb4a083baea"
Template: "d02f35f4-977c-4221-a979-6eb4a083baea"
Path: /sitecore/templates/Project/nov/NOV Shared/Components/Product Repository/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{EE8C3DEC-23A0-4D04-ADF2-17B5BE1A05BE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181119T183200Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e8d3f22b-18ba-4902-87b9-acf2aab265d8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210104T173554Z
