import { HeaderProps } from './Header';

// Realistically this is going to have a lot more data from Sitecore or XM Cloud, but this is a good example mock data set.
const defaultData: HeaderProps = {
  uid: '481a6dc8-de4a-4904-83b7-dff3d2c364a5',
  componentName: 'Header',
  dataSource: '',
  params: {
    CacheClearingBehavior: 'Clear on publish',
  },
  fields: {
    siteFeaturedHeadline: {
      value: 'Our Company Structure',
    },
    siteLogo: {
      value: {
        src: 'https://edge.sitecorecloud.io/nationaloile493-nov-dev-59ee/media/nov/nov-red-and-grey-logo.svg?h=24&iar=0&w=56',
        alt: 'nov',
        width: '56',
        height: '24',
      },
    },
    siteLogoTransparent: {
      value: {
        src: 'https://edge.sitecorecloud.io/nationaloile493-nov-dev-59ee/media/nov/nov-red-and-grey-logo.svg?h=24&iar=0&w=56',
        alt: 'nov',
        width: '56',
        height: '24',
      },
    },
    menuLabel: {
      value: 'Menu',
    },
    siteFeaturedAbstract: {
      value:
        'Our family of companies is organized to provide expert solutions, equipment, and operational support to optimize your drilling and production operations.',
    },
    siteFeaturedCtaLink: {
      value: {
        href: '/en-US/About/Our-Company-Structure',
        text: '',
        linktype: 'internal',
        url: '/en-US/About/Our-Company-Structure',
        anchor: '',
        target: '',
      },
    },
    siteFeaturedCtatext: {
      value: 'Learn More',
    },
    learnMoreText: {
      value: 'Read More',
    },
    portalHeader: {
      value: 'MYNOV is a single sign-on solution.',
    },
    portalDescription: {
      value: 'Access multiple NOV applications and services with one login.',
    },
    portalRegisterUrl: {
      value: {
        href: '',
        text: 'Register here',
        linktype: 'internal',
        url: '',
        anchor: '',
        target: '_blank',
      },
    },
    portalRegisterUrlText: {
      value: 'Sign in',
    },
    portalLoginUrl: {
      value: {
        href: '',
        text: 'Sign in',
        linktype: 'internal',
        url: '',
        anchor: '',
        target: '_blank',
      },
    },
    portalLoginText: null,
    viewAllText: {
      value: 'View All',
    },
    cardImage: {
      value: {
        src: 'https://edge.sitecorecloud.io/nationaloile493-nov-dev-59ee/media/nov/nov-red-and-grey-logo.svg?h=24&iar=0&w=56',
        alt: 'nov',
        width: '56',
        height: '24',
      },
    },
    cardImageAlt: null,
    navigationEntries: [
      {
        subPages: [
          {
            subPages: [
              {
                subPages: [],
                pageImage: null,
                cardImage: {
                  value: {
                    src: 'https://edge.sitecorecloud.io/nationaloile493-nov-dev-59ee/media/nov/nov-red-and-grey-logo.svg?h=24&iar=0&w=56',
                    alt: 'nov',
                    width: '56',
                    height: '24',
                  },
                },
                cardImageAlt: null,
                colorCode: null,
                cssClass: null,
                featuredItem: null,
                templateId: '1bf45569-a9ee-482e-8c1f-6aed83c3c8ab',
                itemId: '9ca3054d-7fc8-46c7-ba1c-cc91a9b92c27',
                url: {
                  value: {
                    href: 'http://xmcloudcm.localhost/en-US/About/Events/Clayshoot-Tournament',
                  },
                },
                headline: {
                  value: 'NOV Sporting Clays Tournament',
                },
                abstract: null,
                menuTitle: {
                  value: 'NOV Clayshoot Tournament',
                },
                mobileMenuTitle: {
                  value: 'NOV Clayshoot Tournament',
                },
                subMenuText: {
                  value: '',
                },
                isActive: false,
                linkToFirstChild: false,
                hideInNavigation: false,
                hideInFooterNavigation: false,
                hideSubNavigation: false,
                target: null,
                featuredStoryHeadline: null,
                featuredStoryAbstract: null,
                featuredStoryCTALink: null,
                featuredStoryCTALinkTarget: null,
                featuredStoryCTAText: null,
                hasSubPages: false,
              },
              {
                subPages: [],
                pageImage: null,
                cardImage: null,
                cardImageAlt: null,
                colorCode: null,
                cssClass: null,
                featuredItem: null,
                templateId: '1bf45569-a9ee-482e-8c1f-6aed83c3c8ab',
                itemId: 'a64c2a11-7a84-42e7-b8ad-aea99934a4bd',
                url: null,
                headline: {
                  value: '14th Annual Golf Tournament',
                },
                abstract: null,
                menuTitle: {
                  value: 'Golf Tournament',
                },
                mobileMenuTitle: {
                  value: 'Golf Tournament',
                },
                subMenuText: {
                  value: '',
                },
                isActive: false,
                linkToFirstChild: false,
                hideInNavigation: false,
                hideInFooterNavigation: false,
                hideSubNavigation: false,
                target: null,
                featuredStoryHeadline: null,
                featuredStoryAbstract: null,
                featuredStoryCTALink: null,
                featuredStoryCTALinkTarget: null,
                featuredStoryCTAText: null,
                hasSubPages: false,
              },
              {
                subPages: [],
                pageImage: null,
                cardImage: null,
                cardImageAlt: null,
                colorCode: null,
                cssClass: null,
                featuredItem: null,
                templateId: '1bf45569-a9ee-482e-8c1f-6aed83c3c8ab',
                itemId: '4dbf6b85-c8b0-493c-a872-d3709ef52735',
                url: null,
                headline: {
                  value: '29th Annual NOV Coiled Tubing Golf Invitational',
                },
                abstract: null,
                menuTitle: {
                  value: '29th Annual NOV Coiled Tubing Golf Invitational',
                },
                mobileMenuTitle: {
                  value: '29th Annual NOV Coiled Tubing Golf Invitational',
                },
                subMenuText: {
                  value: '',
                },
                isActive: false,
                linkToFirstChild: false,
                hideInNavigation: false,
                hideInFooterNavigation: false,
                hideSubNavigation: false,
                target: null,
                featuredStoryHeadline: null,
                featuredStoryAbstract: null,
                featuredStoryCTALink: null,
                featuredStoryCTALinkTarget: null,
                featuredStoryCTAText: null,
                hasSubPages: false,
              },
              {
                subPages: [],
                pageImage: null,
                cardImage: null,
                cardImageAlt: null,
                colorCode: null,
                cssClass: null,
                featuredItem: null,
                templateId: '1bf45569-a9ee-482e-8c1f-6aed83c3c8ab',
                itemId: '7c0c8088-2293-4624-af36-a972d49bc7c7',
                url: null,
                headline: {
                  value: 'NOV and Odessa Pumps - A DistributionNOW company, Equipment Showcase',
                },
                abstract: null,
                menuTitle: {
                  value: 'NOV and Odessa Pumps - A DistributionNOW company, Equipment Showcase',
                },
                mobileMenuTitle: {
                  value: 'NOV and Odessa Pumps - A DistributionNOW company, Equipment Showcase',
                },
                subMenuText: {
                  value: '',
                },
                isActive: false,
                linkToFirstChild: false,
                hideInNavigation: false,
                hideInFooterNavigation: false,
                hideSubNavigation: false,
                target: null,
                featuredStoryHeadline: null,
                featuredStoryAbstract: null,
                featuredStoryCTALink: null,
                featuredStoryCTALinkTarget: null,
                featuredStoryCTAText: null,
                hasSubPages: false,
              },
              {
                subPages: [],
                pageImage: null,
                cardImage: null,
                cardImageAlt: null,
                colorCode: null,
                cssClass: null,
                featuredItem: null,
                templateId: '1bf45569-a9ee-482e-8c1f-6aed83c3c8ab',
                itemId: '5d3839ad-ec66-4229-8623-7248b6330588',
                url: null,
                headline: {
                  value: 'NOV Technology Seminar',
                },
                abstract: null,
                menuTitle: {
                  value: 'NOV Technology Seminar',
                },
                mobileMenuTitle: {
                  value: 'NOV Technology Seminar',
                },
                subMenuText: {
                  value: '',
                },
                isActive: false,
                linkToFirstChild: false,
                hideInNavigation: false,
                hideInFooterNavigation: false,
                hideSubNavigation: false,
                target: null,
                featuredStoryHeadline: null,
                featuredStoryAbstract: null,
                featuredStoryCTALink: null,
                featuredStoryCTALinkTarget: null,
                featuredStoryCTAText: null,
                hasSubPages: false,
              },
              {
                subPages: [],
                pageImage: null,
                cardImage: null,
                cardImageAlt: null,
                colorCode: null,
                cssClass: null,
                featuredItem: null,
                templateId: '1bf45569-a9ee-482e-8c1f-6aed83c3c8ab',
                itemId: 'a14d1c94-d8ed-4a17-90c4-27e7cb334e69',
                url: null,
                headline: {
                  value: 'DUG Haynesville Conference and Exhibition',
                },
                abstract: null,
                menuTitle: {
                  value: 'DUG Haynesville Conference and Exhibition',
                },
                mobileMenuTitle: {
                  value: 'DUG Haynesville Conference and Exhibition',
                },
                subMenuText: {
                  value: '',
                },
                isActive: false,
                linkToFirstChild: false,
                hideInNavigation: false,
                hideInFooterNavigation: false,
                hideSubNavigation: false,
                target: null,
                featuredStoryHeadline: null,
                featuredStoryAbstract: null,
                featuredStoryCTALink: null,
                featuredStoryCTALinkTarget: null,
                featuredStoryCTAText: null,
                hasSubPages: false,
              },
            ],
            pageImage: null,
            cardImage: null,
            cardImageAlt: null,
            colorCode: null,
            cssClass: null,
            featuredItem: null,
            templateId: '800ef4cb-3273-4756-ad58-fd9b119e02bf',
            itemId: 'cd0214ea-b2e7-40a9-89d9-695cdf04c498',
            url: null,
            headline: {
              value: 'Industry Events',
            },
            abstract: null,
            menuTitle: {
              value: 'Industry Events',
            },
            mobileMenuTitle: {
              value: 'Industry Events',
            },
            subMenuText: {
              value: '',
            },
            isActive: false,
            linkToFirstChild: false,
            hideInNavigation: false,
            hideInFooterNavigation: false,
            hideSubNavigation: true,
            target: null,
            featuredStoryHeadline: null,
            featuredStoryAbstract: null,
            featuredStoryCTALink: null,
            featuredStoryCTALinkTarget: null,
            featuredStoryCTAText: null,
            hasSubPages: false,
          },
          {
            subPages: [],
            pageImage: null,
            cardImage: null,
            cardImageAlt: null,
            colorCode: null,
            cssClass: null,
            featuredItem: null,
            templateId: '800ef4cb-3273-4756-ad58-fd9b119e02bf',
            itemId: '8dfd8a57-77e4-4e4e-a720-8f569a679339',
            url: null,
            headline: {
              value: 'News',
            },
            abstract: null,
            menuTitle: {
              value: 'News',
            },
            mobileMenuTitle: {
              value: 'News',
            },
            subMenuText: {
              value: '',
            },
            isActive: false,
            linkToFirstChild: false,
            hideInNavigation: false,
            hideInFooterNavigation: false,
            hideSubNavigation: true,
            target: null,
            featuredStoryHeadline: null,
            featuredStoryAbstract: null,
            featuredStoryCTALink: null,
            featuredStoryCTALinkTarget: null,
            featuredStoryCTAText: null,
            hasSubPages: false,
          },
          {
            subPages: [],
            pageImage: null,
            cardImage: null,
            cardImageAlt: null,
            colorCode: null,
            cssClass: null,
            featuredItem: null,
            templateId: '800ef4cb-3273-4756-ad58-fd9b119e02bf',
            itemId: 'e45fb92c-04ca-4173-b0ad-18007c3f3df3',
            url: null,
            headline: {
              value: 'Live Shows from NOV',
            },
            abstract: null,
            menuTitle: {
              value: 'NOV Live',
            },
            mobileMenuTitle: {
              value: 'NOV Live',
            },
            subMenuText: {
              value: '',
            },
            isActive: false,
            linkToFirstChild: false,
            hideInNavigation: false,
            hideInFooterNavigation: false,
            hideSubNavigation: false,
            target: null,
            featuredStoryHeadline: null,
            featuredStoryAbstract: null,
            featuredStoryCTALink: null,
            featuredStoryCTALinkTarget: null,
            featuredStoryCTAText: null,
            hasSubPages: false,
          },
        ],
        pageImage: null,
        cardImage: {
          value: {
            url: '/nov/Images/About/We-Are-NOV-About/NOV-employee-on-rigsite.jpg',
            alt: 'Service technician looking at rigsite',
            height: '295',
            width: '514',
          },
        },
        cardImageAlt: null,
        colorCode: null,
        cssClass: null,
        featuredItem: null,
        templateId: 'd227ab0e-fd44-4ae0-878a-189949913d0b',
        itemId: '784dd9e8-c40d-47f4-accf-893251b02eb3',
        url: null,
        headline: {
          value: 'About Us',
        },
        abstract: null,
        menuTitle: {
          value: 'About Us',
        },
        mobileMenuTitle: {
          value: 'About Us',
        },
        subMenuText: {
          value: '',
        },
        isActive: false,
        linkToFirstChild: false,
        hideInNavigation: true,
        hideInFooterNavigation: false,
        hideSubNavigation: false,
        target: null,
        featuredStoryHeadline: {
          value: 'About Us',
        },
        featuredStoryAbstract: {
          value:
            'Every day, the oil and gas industry’s best minds put more than 150 years of experience to work to help our customers achieve lasting success. We have the people, capabilities, and vision to serve the needs of a challenging and evolving industry. One the world can’t live without.',
        },
        featuredStoryCTALink: {
          value: {
            href: '/en-US/About',
            text: 'Learn more',
            linktype: 'internal',
            url: '/en-US/About',
            anchor: '',
            target: '',
          },
        },
        featuredStoryCTALinkTarget: null,
        featuredStoryCTAText: {
          value: 'About Us',
        },
        hasSubPages: true,
      },
    ],
  },
};

export const noData = {
  render: {},
  params: [],
};

export default defaultData;
