---
ID: "3cd9d0ad-f59f-4d23-92f3-d1a4ecacb1dc"
Parent: "4144f5f9-b8b1-4358-a093-81cc6abc35cf"
Template: "569afdf0-3638-43a2-8a58-c569799c1bf7"
Path: /sitecore/content/nov/nov/Data/Modules/About/News/New side entry mixer provides reliability and easier maintenance in large volume vessel applications
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200918T145528Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "74d3583a-1095-45ef-be19-bfe6939f84df"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200918T145528Z
