---
ID: "fbc1af39-1573-4c95-8493-f126ca6dcbd3"
Parent: "3609914e-4a9b-4ff0-833b-3ae878079c30"
Template: "3609914e-4a9b-4ff0-833b-3ae878079c30"
Path: /sitecore/templates/Feature/NOV Com/Modules/Hero Modules/Hero Slide/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181004T183722Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0fef9cd1-ad9c-4c58-b82f-75862c1e37ed"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190124T013517Z
