---
ID: "7039e13a-966f-4de3-9be9-9537462e3eb3"
Parent: "c59ac73c-92df-4450-84d3-d6e20e242056"
Template: "a42be250-5aa9-4984-a08b-0a88e538acc0"
Path: /sitecore/content/nov/nov/Data/Modules/About/Our Company Structure/RIG/Rig Technologies Supplier Resources/Training/Training D13 Hover Image
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "042aa8d7-4dff-44d2-b316-177ccc7fe3e7"
      Hint: body3
      Value: Understand our strategy for developing the ideal NOV supplier.
    - ID: "1d75ac17-3b90-4147-be3b-68f7c844017f"
      Hint: headline3
      Value: Supplier Relationship Management
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200706T190752Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{37CE6828-491E-4AF1-A858-254564BEE5B8}"
    - ID: "3f427f31-5ae2-4eb7-b01a-a9eb09e3fe47"
      Hint: cta2
      Value: |
        <link class="" querystring="" id="{04631E53-81DD-41BC-AA33-074BB4A1C3CF}" anchor="" target="" title="" linktype="internal" text="Learn more" url="/NOV Com/Home/About/Our Company Structure/RIG/Rig Technologies Supplier Resources/Procurement" />
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jeremygrzywa
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jeremygrzywa
    - ID: "6448a25f-1cf7-4c4a-9b99-f0a7b205764d"
      Hint: headline2
      Value: Procurement
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e562e9e5-ca93-4586-9428-5b21b8a03449"
    - ID: "97b737d5-e611-423a-ae3f-e98eb69fd090"
      Hint: image1
      Value: |
        <image mediaid="{DFF04AAA-4513-4FD5-9F4E-30F6F00E1AFE}" cropregion="1627,0,2330,1080" ratio="393:600" width="393" height="600" alt="" hspace="" vspace="" />
    - ID: "9c6e71f7-4cf3-4ef6-ab11-dc1f89a31a29"
      Hint: headline1
      Value: Rig Technologies Supplier Resources
    - ID: "b955311a-73da-4c61-adda-1b6e24665d63"
      Hint: cta1
      Value: |
        <link class="" querystring="" id="{744E0B44-8E50-460C-8E59-BA7C08AC5A6E}" anchor="" target="" title="" linktype="internal" text="Learn more" url="/NOV Com/Home/About/Our Company Structure/RIG/Rig Technologies Supplier Resources" />
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "ce25f5fe-d974-4b7a-a13d-b1e135ea53ad"
      Hint: image2
      Value: |
        <image mediaid="{6C7D3E76-290E-41F8-A29E-461F6CE41BBC}" cropregion="540,0,1378,1280" ratio="393:600" width="393" height="600" />
    - ID: "d3d4c3a9-9927-4a25-abfa-c7a3e9dc65db"
      Hint: image3
      Value: |
        <image mediaid="{4FFE8F86-EA52-4464-9A41-E97543E2161A}" cropregion="540,0,1378,1280" ratio="393:600" width="393" height="600" />
    - ID: "d4f2e5cb-0c8c-4e04-a7a7-875b529e21c3"
      Hint: body1
      Value: Learn how to become a successful partner to NOV Rig Technologies.
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230706T172646Z
    - ID: "e6f374a5-5af2-4c17-ad70-1c7514edc276"
      Hint: cta3
      Value: |
        <link class="" querystring="" id="{FCDAFD43-20B6-4B98-9B02-E0E156329899}" anchor="" target="" title="" linktype="internal" text="Learn more" url="/NOV Com/Home/About/Our Company Structure/RIG/Rig Technologies Supplier Resources/Supplier Relationship Management" />
    - ID: "f07d95f3-950f-48a4-af60-589eeaac2e95"
      Hint: body2
      Value: Discover what you need to know to conduct business with us and meet our exacting requirements.
