---
ID: "072c12cb-32cd-4ffc-b8f5-587aa12c5ced"
Parent: "d1074c40-2825-4904-b6f4-c2043506ca7a"
Template: "d1074c40-2825-4904-b6f4-c2043506ca7a"
Path: /sitecore/templates/Project/nov/NOV Com/Modules/Content Block Testimonial/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181018T211246Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0ccbc836-c92f-44f4-82f8-304c27d46650"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181206T201413Z
