---
ID: "8964f93b-a4a8-4136-80c6-e8977a2a52e7"
Parent: "e5112584-0b89-4c00-8f1d-b9f7e901c5b3"
Template: "c0aa2bad-85b9-47e4-a236-901c3115fb87"
Path: /sitecore/content/nov/nov/Data/Modules/Products/WBT/Grant Prideco/Thread Compound Application/Thread Compound Application_J5 Features List
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190314T191706Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\heatherbaxter
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\heatherbaxter
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2c7792a0-be6a-47ba-8c64-e097b4da714c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\heatherbaxter
    - ID: "c3afee16-1dbc-4a49-8037-9d03d0d7d62e"
      Hint: description
      Value: |
        <h2>Best practices for thread compound application</h2>
        <h3>Clean connection surface</h3>
        <p>Make sure that the threads, as well as the primary and secondary shoulder of the pin and box, are clean and free of drilling fluids/solids. Thread compound adheres best to a clean surface. Additionally, drilling fluids/solids pose a risk for micro-washout. It may be necessary to rinse drilling fluid off threads before applying compound.</p>
        <h3>Thread compound selection</h3>
        <p>We do not endorse any particular thread compound brand or product over another. However, we do recommend the use of a <strong>copper-based</strong> thread compound for the following reasons:</p>
        <ul>
            <li>Comes with increased friction factor</li>
            <li>Generally shows better galling resistance</li>
        </ul>
        <h3>Proper thread compound application</h3>
        <p>Use a good-quality brush that does not lose its hair (which can create a channel for micro-washout when trapped between sealing shoulders). Before makeup, the following surfaces of pins and boxes must be coated with a good-quality thread compound:</p>
        <ul>
            <li>Threads (about <sup>1</sup>/<sub>3</sub> of thread height)</li>
            <li>Primary shoulder</li>
            <li>Secondary shoulder when applicable (double-shouldered connections)</li>
            <li>Metal-to-metal seal when applicable (XT-M™, XT-MF™, TT-M™, TF-M™, CT-M™, GT-M™, MaXit™, VX-M™, DPR HP™)</li>
        </ul>
        <p>Be sure to <strong>fully</strong> coat both the pin and box. Thread compound will not spread out when connections are made-up. Proper thread compound application must be done before make-up.</p>
        <h3>When to apply thread compound</h3>
        <p>Pins and boxes must receive fresh compound. Common practice is as follows:</p>
        <ul>
            <li>Apply on boxes during POOH (pull-out-of-hole)</li>
            <li>Apply on pins during RIH (run-in-hole)</li>
        </ul>
        <p>Racking pipe stands will wipe thread compound off the pin nose of a double-shouldered connection. Ensure that full application of thread compound has been achieved just before makeup.</p>
        <h3>Thread compound friction factor</h3>
        <p>The thread compound friction factor (FF) reflects a compound’s resistance to torquing. The higher the FF, the more torque can be applied to load the connection with the same stress. Unless otherwise specified, our documents show makeup torque based on an FF of 1.0. Multiply our torque values (with 1.0 FF) by the compound supplier FF value (without exceeding 1.15).</p>
        <p><strong>Example:</strong> Recommended MUT for XT 39 (5 × 29/16 in.) with 1.0 FF compound is 24,500 ft-lb.</p>
        <ul>
            <li>With 1.10 FF, apply 26,900 ft-lb (1.10 × 24,500)</li>
            <li>With 1.20 FF, apply 28,175 ft-lb (1.15 × 24,500)</li>
        </ul>
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190314T193626Z
  - Version: 2
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190314T204310Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\heatherbaxter
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\heatherbaxter
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ed07405b-89af-40ad-9aa3-8f2d408ef21e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\heatherbaxter
    - ID: "c3afee16-1dbc-4a49-8037-9d03d0d7d62e"
      Hint: description
      Value: |
        <h2>Best practices for thread compound application</h2>
        <h3>Clean connection surface</h3>
        <p>Make sure that the threads, as well as the primary and secondary shoulder of the pin and box, are clean and free of drilling fluids/solids. Thread compound adheres best to a clean surface. Additionally, drilling fluids/solids pose a risk for micro-washout. It may be necessary to rinse drilling fluid off threads before applying compound.</p>
        <h3>Thread compound selection</h3>
        <p>We do not endorse any particular thread compound brand or product over another. However, we do recommend the use of a <strong>copper-based</strong> thread compound for the following reasons:</p>
        <ul>
            <li>Comes with increased friction factor</li>
            <li>Generally shows better galling resistance</li>
        </ul>
        <h3>Proper thread compound application</h3>
        <p>Use a good-quality brush that does not lose its hair (which can create a channel for micro-washout when trapped between sealing shoulders). Before makeup, the following surfaces of pins and boxes must be coated with a good-quality thread compound:</p>
        <ul>
            <li>Threads (about <sup>1</sup>/<sub>3</sub> of thread height)</li>
            <li>Primary shoulder</li>
            <li>Secondary shoulder when applicable (double-shouldered connections)</li>
            <li>Metal-to-metal seal when applicable (XT-M&trade;, XT-MF&trade;, TT-M&trade;, TF-M&trade;, CT-M&trade;, GT-M&trade;, MaXit&trade;, VX-M&trade;, DPR HP&trade;)</li>
        </ul>
        <p>Be sure to <strong>fully</strong> coat both the pin and box. Thread compound will not spread out when connections are made-up. Proper thread compound application must be done before make-up.</p>
        <h3>When to apply thread compound</h3>
        <p>Pins and boxes must receive fresh compound. Common practice is as follows:</p>
        <ul>
            <li>Apply on boxes during POOH (pull-out-of-hole).</li>
            <li>Apply on pins during RIH (run-in-hole).</li>
        </ul>
        <p>Racking pipe stands will wipe thread compound off the pin nose of a double-shouldered connection. Ensure that full application of thread compound has been achieved just before makeup.</p>
        <h3>Thread compound friction factor</h3>
        <p>The thread compound friction factor (FF) reflects a compound&rsquo;s resistance to torquing. The higher the FF, the more torque can be applied to load the connection with the same stress. Unless otherwise specified, our documents show makeup torque based on an FF of 1.0. Multiply our torque values (with 1.0 FF) by the compound supplier FF value (without exceeding 1.15).</p>
        <p><strong>Example:</strong> Recommended MUT for XT 39 (5 &times; 29/16 in.) with 1.0 FF compound is 24,500 ft-lb.</p>
        <ul>
            <li>With 1.10 FF, apply 26,900 ft-lb (1.10 &times; 24,500).</li>
            <li>With 1.20 FF, apply 28,175 ft-lb (1.15 &times; 24,500).</li>
        </ul>
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20190314T204310Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190314T204324Z
  - Version: 3
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190325T201126Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\heatherbaxter
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\heatherbaxter
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eed9efd8-63d7-40d1-b3da-4550d56065da"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\heatherbaxter
    - ID: "c3afee16-1dbc-4a49-8037-9d03d0d7d62e"
      Hint: description
      Value: |
        <h2>Best practices for thread compound application</h2>
        <h3>Clean connection surface</h3>
        <p>Make sure that the threads, as well as the primary and secondary shoulder of the pin and box, are clean and free of drilling fluids/solids. Thread compound adheres best to a clean surface. Additionally, drilling fluids/solids pose a risk for micro-washout. It may be necessary to rinse drilling fluid off threads before applying compound.</p>
        <h3>Thread compound selection</h3>
        <p>We do not endorse any particular thread compound brand or product over another. However, we do recommend the use of a <strong>copper-based</strong> thread compound for the following reasons:</p>
        <ul>
            <li>Comes with increased friction factor</li>
            <li>Generally shows better galling resistance</li>
        </ul>
        <h3>Proper thread compound application</h3>
        <p>Use a good-quality brush that does not lose its hair (which can create a channel for micro-washout when trapped between sealing shoulders). Before makeup, the following surfaces of pins and boxes must be coated with a good-quality thread compound:</p>
        <ul>
            <li>Threads (about <sup>1</sup>/<sub>3</sub> of thread height)</li>
            <li>Primary shoulder</li>
            <li>Secondary shoulder when applicable (double-shouldered connections)</li>
            <li>Metal-to-metal seal when applicable (XT-M&trade;, XT-MF&trade;, TT-M&trade;, TF-M&trade;, CT-M&trade;, GT-M&trade;, MaXit&trade;, VX-M&trade;, DPR HP&trade;)</li>
        </ul>
        <br />
        <p>Be sure to <strong>fully</strong> coat both the pin and box. Thread compound will not spread out when connections are made-up. Proper thread compound application must be done before make-up.</p>
        <h3>When to apply thread compound</h3>
        <p>Pins and boxes must receive fresh compound. Common practice is as follows:</p>
        <ul>
            <li>Apply on boxes during POOH (pull-out-of-hole).</li>
            <li>Apply on pins during RIH (run-in-hole).</li>
        </ul>
        <br />
        <p>Racking pipe stands will wipe thread compound off the pin nose of a double-shouldered connection. Ensure that full application of thread compound has been achieved just before makeup.</p>
        <h3>Thread compound friction factor</h3>
        <p>The thread compound friction factor (FF) reflects a compound&rsquo;s resistance to torquing. The higher the FF, the more torque can be applied to load the connection with the same stress. Unless otherwise specified, our documents show makeup torque based on an FF of 1.0. Multiply our torque values (with 1.0 FF) by the compound supplier FF value (without exceeding 1.15).</p>
        <p><strong>Example:</strong> Recommended MUT for XT 39 (5 &times; 29/16 in.) with 1.0 FF compound is 24,500 ft-lb.</p>
        <ul>
            <li>With 1.10 FF, apply 26,900 ft-lb (1.10 &times; 24,500).</li>
            <li>With 1.20 FF, apply 28,175 ft-lb (1.15 &times; 24,500).</li>
        </ul>
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20190325T201126Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190325T201159Z
  - Version: 4
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190402T163116Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\heatherbaxter
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\heatherbaxter
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "26c6a8b7-7543-4852-b46d-8e9254884079"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\heatherbaxter
    - ID: "c3afee16-1dbc-4a49-8037-9d03d0d7d62e"
      Hint: description
      Value: |
        <h2>Best practices for thread compound application</h2>
        <h3>Clean connection surface</h3>
        <p>Make sure that the threads, as well as the primary and secondary shoulder of the pin and box, are clean and free of drilling fluids/solids. Thread compound adheres best to a clean surface. Additionally, drilling fluids/solids pose a risk for micro-washout. It may be necessary to rinse drilling fluid off threads before applying compound.</p>
        <h3>Thread compound selection</h3>
        <p>We do not endorse any particular thread compound brand or product over another. However, we do recommend the use of a <strong>copper-based</strong> thread compound for the following reasons:</p>
        <ul>
            <li>Comes with increased friction factor</li>
            <li>Generally shows better galling resistance</li>
        </ul>
        <h3>Proper thread compound application</h3>
        <p>Use a good-quality brush that does not lose its hair (which can create a channel for micro-washout when trapped between sealing shoulders). Before makeup, the following surfaces of pins and boxes must be coated with a good-quality thread compound:</p>
        <ul>
            <li>Threads (about <sup>1</sup>/<sub>3</sub> of thread height)</li>
            <li>Primary shoulder</li>
            <li>Secondary shoulder when applicable (double-shouldered connections)</li>
            <li>Metal-to-metal seal when applicable (XT-M&trade;, XT-MF&trade;, TT-M&trade;, TF-M&trade;, CT-M&trade;, GT-M&trade;, MaXit&trade;, VX-M&trade;, DPR HP&trade;)</li>
        </ul>
        <p>Be sure to <strong>fully</strong> coat both the pin and box. Thread compound will not spread out when connections are made-up. Proper thread compound application must be done before make-up.</p>
        <h3>When to apply thread compound</h3>
        <p>Pins and boxes must receive fresh compound. Common practice is as follows:</p>
        <ul>
            <li>Apply on boxes during POOH (pull-out-of-hole).</li>
            <li>Apply on pins during RIH (run-in-hole).</li>
        </ul>
        <p>Racking pipe stands will wipe thread compound off the pin nose of a double-shouldered connection. Ensure that full application of thread compound has been achieved just before makeup.</p>
        <h3>Thread compound friction factor</h3>
        <p>The thread compound friction factor (FF) reflects a compound&rsquo;s resistance to torquing. The higher the FF, the more torque can be applied to load the connection with the same stress. Unless otherwise specified, our documents show makeup torque based on an FF of 1.0. Multiply our torque values (with 1.0 FF) by the compound supplier FF value (without exceeding 1.15).</p>
        <p><strong>Example:</strong> Recommended MUT for XT 39 (5 &times; 29/16 in.) with 1.0 FF compound is 24,500 ft-lb.</p>
        <ul>
            <li>With 1.10 FF, apply 26,900 ft-lb (1.10 &times; 24,500).</li>
            <li>With 1.20 FF, apply 28,175 ft-lb (1.15 &times; 24,500).</li>
        </ul>
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20190402T163116Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190402T163158Z
