schema:
  - './src/temp/GraphQLIntrospectionResult.json'
documents: 'src/**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typed-document-node
cacheDir: .generated/graphql
config:
  useIndexSignature: true
