---
ID: "022d77f9-d17f-4852-8a77-9ee8492d6c25"
Parent: "005eebd6-d10c-4010-b031-2f3de6b21f47"
Template: "5030864f-eb96-4da7-a417-e5a0108c59f8"
Path: /sitecore/content/nov/nov/Data/Modules/Products/WBT/WellSite Services/Mud Conditioners/COBRA Mud Conditioner J6 Product Table Typical Configs
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190717T181036Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\charisgamroth
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\charisgamroth
    - ID: "89e0d08a-ef09-4651-9d48-1e619efc4cb2"
      Hint: table
      Value: |
        <table>
            <tbody>
                <tr>
                    <td></td>
                    <td><strong>Quantity Desilter Cones (4-in.)</strong></td>
                    <td><strong>Quantity Desander Cones (12-in.)</strong></td>
                    <td><strong>Hydrocyclone Capacity</strong></td>
                </tr>
                <tr>
                    <td>COBRA 16/2 Mud Conditioner</td>
                    <td>16</td>
                    <td>2</td>
                    <td>1,000 gal/min (3785 L/min)</td>
                </tr>
                <tr>
                    <td>KING COBRA 16/2 Mud Conditioner</td>
                    <td>16</td>
                    <td>2</td>
                    <td>1,000 gal/min (3785 L/min)</td>
                </tr>
                <tr>
                    <td>KING COBRA 24/3 Mud Conditioner</td>
                    <td>24</td>
                    <td>3</td>
                    <td>1,500 gal/min (5678 L/min)</td>
                </tr>
            </tbody>
        </table>
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fac3c8d4-9350-489d-9007-85f5f017257f"
    - ID: "915a3100-b6af-4b83-a168-471e1b3e74be"
      Hint: headline
      Value: Typical Mud Conditioner Configurations
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\charisgamroth
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190717T182041Z
