---
ID: "82088ebe-9b67-4b42-a7e1-7e4681f2bb38"
Parent: "005eebd6-d10c-4010-b031-2f3de6b21f47"
Template: "5030864f-eb96-4da7-a417-e5a0108c59f8"
Path: /sitecore/content/nov/nov/Data/Modules/Products/WBT/WellSite Services/Mud Conditioners/King Cobra Mud Conditioner_J6 Product Table_3 Typical Configurations
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190705T152446Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\heatherbaxter
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\heatherbaxter
    - ID: "89e0d08a-ef09-4651-9d48-1e619efc4cb2"
      Hint: table
      Value: |
        <table>
            <tbody>
                <tr>
                    <td>&nbsp;</td>
                    <td>Quantity desilter cones (4-in.)</td>
                    <td>Quantity desander cones (12-in.)</td>
                    <td>Hydrocyclone capacity</td>
                </tr>
                <tr>
                    <td>COBRA 16/2 Mud Conditioner</td>
                    <td>16</td>
                    <td>2</td>
                    <td>1,000 gal/min<br />
                    (3785 L/min)</td>
                </tr>
                <tr>
                    <td>KING COBRA 16/2 Mud Conditioner</td>
                    <td>16</td>
                    <td>2</td>
                    <td>1,000 gal/min<br />
                    (3785 L/min)</td>
                </tr>
                <tr>
                    <td>KING COBRA 24/3 Mud Conditioner</td>
                    <td>24</td>
                    <td>3</td>
                    <td>1,500 gal/min<br />
                    (5678 L/min)</td>
                </tr>
            </tbody>
        </table>
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1927dcb9-cfa8-4708-991e-0b9cdba93a0c"
    - ID: "915a3100-b6af-4b83-a168-471e1b3e74be"
      Hint: headline
      Value: Typical Mud Conditioner Configurations
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\heatherbaxter
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190705T152807Z
  - Version: 2
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190705T152918Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\heatherbaxter
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\heatherbaxter
    - ID: "89e0d08a-ef09-4651-9d48-1e619efc4cb2"
      Hint: table
      Value: |
        <table>
            <tbody>
                <tr>
                    <td>Mud conditioners</td>
                    <td><strong>COBRA 16/2</strong></td>
                    <td><strong>KING COBRA 16/2</strong></td>
                    <td><strong>KING COBRA 24/3</strong></td>
                </tr>
                <tr>
                    <td>Quantity desilter cones (4-in.)</td>
                    <td>16</td>
                    <td>16</td>
                    <td>24</td>
                </tr>
                <tr>
                    <td>Quantity desander cones (12-in.)</td>
                    <td>2</td>
                    <td>2</td>
                    <td>3</td>
                </tr>
                <tr>
                    <td>Hydrocyclone capacity</td>
                    <td>1,000 gal/min<br />
                    (3785 L/min)<br />
                    </td>
                    <td>1,000 gal/min<br />
                    (3785 L/min)<br />
                    </td>
                    <td>1,500 gal/min<br />
                    (5678 L/min)<br />
                    </td>
                </tr>
                <tr>
                    <td>L &times; W &times; H</td>
                    <td>106 &times; 80 &times; 101 in. <br />
                    (2692 &times; 2032 &times; 2565 mm)</td>
                    <td>120 &times; 87 &times; 106 in. <br />
                    (3048 &times; 2210 &times; 2692 mm)</td>
                    <td>138 &times; 90 &times; 118 in. <br />
                    (3505 &times; 2286 &times; 2997 mm)</td>
                </tr>
                <tr>
                    <td>Weight</td>
                    <td>6,200 lb (2815 kg)</td>
                    <td>7,900 lb (3587 kg)</td>
                    <td>9,100 lb (4131 kg)</td>
                </tr>
            </tbody>
        </table>
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a21f5ac9-72f7-4fd4-b04b-faa513845559"
    - ID: "915a3100-b6af-4b83-a168-471e1b3e74be"
      Hint: headline
      Value: Typical Mud Conditioner Configurations
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\heatherbaxter
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20190705T152918Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190705T153705Z
  - Version: 3
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190705T195507Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\heatherbaxter
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\heatherbaxter
    - ID: "89e0d08a-ef09-4651-9d48-1e619efc4cb2"
      Hint: table
      Value: |
        <table>
            <tbody>
                <tr>
                    <td>Mud conditioners</td>
                    <td><strong>COBRA 16/2</strong></td>
                    <td><strong>KING COBRA 16/2</strong></td>
                    <td><strong>KING COBRA 24/3</strong></td>
                </tr>
                <tr>
                    <td>Quantity desilter<br />
                    cones (4-in.)</td>
                    <td>16</td>
                    <td>16</td>
                    <td>24</td>
                </tr>
                <tr>
                    <td>Quantity desander<br />
                    cones (12-in.)</td>
                    <td>2</td>
                    <td>2</td>
                    <td>3</td>
                </tr>
                <tr>
                    <td>Hydrocyclone <br />
                    capacity</td>
                    <td>1,000 gal/min<br />
                    (3785 L/min)<br />
                    </td>
                    <td>1,000 gal/min<br />
                    (3785 L/min)<br />
                    </td>
                    <td>1,500 gal/min<br />
                    (5678 L/min)<br />
                    </td>
                </tr>
                <tr>
                    <td>L &times; W &times; H</td>
                    <td>106 &times; 80 &times; 101 in. <br />
                    (2692 &times; 2032 &times; 2565 mm)</td>
                    <td>120 &times; 87 &times; 106 in. <br />
                    (3048 &times; 2210 &times; 2692 mm)</td>
                    <td>138 &times; 90 &times; 118 in. <br />
                    (3505 &times; 2286 &times; 2997 mm)</td>
                </tr>
                <tr>
                    <td>Weight</td>
                    <td>6,200 lb (2815 kg)</td>
                    <td>7,900 lb (3587 kg)</td>
                    <td>9,100 lb (4131 kg)</td>
                </tr>
            </tbody>
        </table>
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "35768273-1734-440d-8bcb-0b9f0fed78c1"
    - ID: "915a3100-b6af-4b83-a168-471e1b3e74be"
      Hint: headline
      Value: Typical Mud Conditioner Configurations
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\heatherbaxter
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20190705T195507Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190705T200009Z
