---
ID: "2994ed75-baae-4614-848a-44a48b364261"
Parent: "18377fcf-d581-4b7a-8c37-198492ba879a"
Template: "18377fcf-d581-4b7a-8c37-198492ba879a"
Path: /sitecore/templates/Project/nov/NOV Shared/Field Sections/Shared Labels/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170306T205730Z
    - ID: "39e6935d-f14d-44a9-9d24-d8a0d653b93a"
      Hint: Label View All
      Value: View All
    - ID: "3dae27d0-163f-434a-a5de-9d6d8454035e"
      Hint: Search Result Download Label
      Value: Download
    - ID: "4d685e2c-5975-40e3-8ebe-4fdc03ad58fb"
      Hint: Label Read More
      Value: Read More
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "63819825-7d7d-4006-8f6e-c63377f7f5e8"
      Hint: Label Product Read More
      Value: View Product
    - ID: "708dae42-95cb-489b-8cdc-e20dc78ab403"
      Hint: Label Of
      Value: of
    - ID: "7b57ada0-2559-4ff2-a2c7-e7675c9e7e89"
      Hint: Label Download
      Value: Download
    - ID: "853f922c-d7a5-473f-8a83-0b2f396ccb00"
      Hint: Label Overview
      Value: Overview
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7e90160c-7932-485a-ba72-9cbd81bd2d3d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d3f70291-3f14-4289-8f1c-0d8613d10b8d"
      Hint: Search Result Read More Label
      Value: Read More
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190510T205651Z
