---
ID: "3dc70c48-ae10-44e0-b13a-81aaf4444b46"
Parent: "c7581147-fda1-48e7-94e1-b7fed7a4f369"
Template: "c7581147-fda1-48e7-94e1-b7fed7a4f369"
Path: /sitecore/templates/Project/nov/NOV Com/Modules/Search Modules/Search Sign Up/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181103T000728Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6164484e-7652-4495-bc1e-bc6c057127e4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181103T000728Z
