---
ID: "9cec2451-3233-4269-b2f5-d16f7de796ea"
Parent: "357b8999-e1c5-4bbb-8295-5087ee84f9bf"
Template: "357b8999-e1c5-4bbb-8295-5087ee84f9bf"
Path: /sitecore/templates/Project/nov/NOV Com/Modules/Soundcloud Player/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181022T174607Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ce37a673-ad2d-4d63-8912-6f26af792180"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181022T174607Z
