---
ID: "d184008d-9482-490b-b39a-292aee8d92d7"
Parent: "c514004e-6f2f-4108-bc06-c27c6d55fe31"
Template: "07c63710-4422-42b9-adb7-67b4bad63607"
Path: /sitecore/content/nov/nov/Data/Modules/About/News/Phoenix Series Drill Bits for Geothermal Drilling Applications/Phoenix Series Drill Bits for Geothermal Drilling Applications D5 Article Text
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "0f10eefb-f9da-4b41-83a0-87900c4e25ed"
      Hint: body
      Value: |
        <p>For many years, tungsten carbide roller cone insert bits were implemented in geothermal drilling applications, as they were believed to be the most effective way to drill hard rock formations. Due to their relatively poor performance and short bit life in hard rocks, polycrystalline diamond compact (PDC) drill bits were previously disregarded in geothermal applications, where impact and thermal-abrasive resistance can be detrimental to their reliability.</p>
        <p>With technological advancements in PDC drill bit design, bit/bottomhole assembly modeling, analytical capabilities, and drilling parameter optimization techniques, issues related to downhole vibrations have been brought under control, which has helped to improve drilling performance.</p>
        <p>One the most significant PDC advances has been the invention of leaching techniques by ReedHycalog in the late 1990s. The leaching of PDC cutter diamond layers improves the cutters&rsquo; thermal and abrasion resistance to unprecedented levels, giving PDC drill bits an edge over roller cone drill bits, even in harsh rock environments. Since then, ReedHycalog has been the pioneer and industry leader in the development of PDC technologies and drill bit solutions.</p>
        <p>Continuing our tradition of providing the latest drilling technologies, ReedHycalog is proud to introduce high-performance drill bits for geothermal drilling applications. Our <a href="-/media/570a41004131496aadf2824ca3d6535c.ashx">Phoenix<sup>TM</sup></a>&nbsp;series drill bits are based on the field-proven, technically advanced Tektonic&trade; drill bit platform, which has been customized to drill farther and faster in hard rock environments.</p>
        <p>Phoenix series drill bits incorporate ION&trade; cutters, which utilize NOV&rsquo;s patented thermal-stabilizing, deep-leach technology with refined diamond feeds and increased sintering pressures that provide denser diamond for increased toughness and abrasion resistance.&nbsp; The result is a high-performance, thermally stable cutter that stays sharper longer by minimizing chipping and breakage common in porous and brittle rock and by reducing wear from typically fine-grain, abrasive formations. The ION platform also offers application- and formation-specific geometries designed for maximizing rock failure by balancing fracturing and shearing rock-failure mechanisms.&nbsp; ION shaped cutters are highly effective and efficient in volcanic rock formations, providing increased drilling efficiency without sacrificing durability.&nbsp;&nbsp;</p>
        <p>Phoenix series bits are custom designed to enhance drilling efficiency in hard rock formations. Our Phoenix drill bits utilize specialized design tools, including computer analysis of torque response, simulations of heat generation and cutter temperature, bit lateral stability analysis, and material enhancements to maximize downhole performance.</p>
        <p>Effective torsional stability is one of the primary objectives when drilling in hard, interbedded formations, and our Phoenix series bits reduce the risk of torsional oscillations through enhanced depth-of-cut control. Using patent-pending components along with an innovative depth-of-cut analysis, our Phoenix bits, along with uniquely shaped cutter geometries, will provide improved torque response in geothermal applications.</p>
        <p>As a leading provider of drill bit solutions to the oil and gas industry, we&rsquo;ve leveraged that same technology and experience to establish our Phoenix series bits in the geothermal market. ReedHycalog has drilled some of the longest and fastest intervals in geothermal wells around the world. From a 67% higher rate of penetration with a single bit run in New Zealand to drilling 8% farther and 36% faster in an Indonesian operation, we&rsquo;re positioned to equip you with the most advanced drilling technologies for your geothermal applications.</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200810T214402Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b8f1f885-ef19-4d49-9c46-18ce9e9886a0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jeremygrzywa
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200819T142917Z
