---
ID: "cd03df84-4430-4503-b035-c364c46164f0"
Parent: "8dfd8a57-77e4-4e4e-a720-8f569a679339"
Template: "93e4c55d-9fa4-4945-a03a-1565852b0a90"
Path: /sitecore/content/nov/nov/Home/About/News/NOV launches premium Pegasus series drill bits for large diameter applications
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{40C0E7ED-9887-49E1-8E89-43D16DD2AD6C}">
        <r
          ds=""
          id="{FA28682B-1CF3-426A-BE1B-F359A64D6282}"
          par="Add Gradient=1&amp;Text Color=white"
          ph="/main/hero-slide-{901672BD-109F-4BA8-9932-A6A9CA1537C0}-0"
          uid="{9B4417AB-C22F-4C76-B2DC-98F2FCA8A71E}" />
        <r
          id="{AB213187-9551-4F9B-AE3D-261BB2B2434F}"
          ph="main"
          uid="{901672BD-109F-4BA8-9932-A6A9CA1537C0}" />
        <r
          ds="{47DA17C6-72D2-4039-BA6F-C295E2BB5FA2}"
          id="{2002D52F-38B0-48F3-8256-F67F34126723}"
          par=""
          ph="main"
          uid="{10CEBA25-FC2A-4F84-8760-9B825D4EAF06}" />
        <r
          ds="{CEB02E26-8A66-4E90-8CBD-2A787E3A8F03}"
          id="{7A39D53C-7601-4537-AFDF-7EB071979666}"
          par=""
          ph="main"
          uid="{37DC6908-9973-4BF3-AA1F-616581927F03}" />
        <r
          ds="{9911D0D9-A0CF-49D5-992D-B9895796CDBA}"
          id="{F6988CA1-8F6A-4235-8851-39729DDF65B4}"
          par="Alignment=right"
          ph="main"
          uid="{3A4E7139-50CB-4BD5-AB2E-460BC7CE5AAF}" />
        <r
          ds="{CFBC8DDE-86B2-4D7D-8BE7-224A7BDB0214}"
          id="{7A39D53C-7601-4537-AFDF-7EB071979666}"
          par=""
          ph="main"
          uid="{29B80482-A671-447F-BB46-8121D422BD81}" />
        <r
          ds="{62EF53C1-2A58-4866-A4F1-2BA183A24B38}"
          id="{2E6C5F1E-BC4A-4FBE-BC72-FBCB237F8DDC}"
          par=""
          ph="main"
          uid="{97344B92-7C95-4AC5-BA52-015B4E4B60A0}" />
        <r
          ds="{BAC4F798-A3A9-4468-96B1-013D049E0AD2}"
          id="{417E0128-4AE1-4E78-ACC9-4820C238DD4F}"
          par=""
          ph="main"
          uid="{7FCE1D2B-E077-4A3D-AF80-996014D9B527}" />
        <r
          ds="{56F9FDA2-D837-44CA-B622-9CA6F5E5DC04}"
          id="{7A39D53C-7601-4537-AFDF-7EB071979666}"
          par=""
          ph="main"
          uid="{B7906B15-B51F-4DDA-9D56-0D4EDD3DF208}" />
        <r
          ds="{3FD459FC-51A8-4BC2-99E1-85C6746D5916}"
          id="{410308FD-D76D-48D4-9E14-E9C56F2AECDF}"
          par=""
          ph="main"
          uid="{9B9C6914-204E-47B8-ABD6-F2712DC7BB72}" />
      </d>
    </r>
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "01fd8c23-1b98-4e4b-9f2d-ecf3eb8aad68"
      Hint: businessUnits
      Value: "{0C44BCB4-A6A1-41FD-AB80-08DB189B3A0D}"
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{3A4E7139-50CB-4BD5-AB2E-460BC7CE5AAF}">
              <p:d />
            </r>
            <r
              uid="{29B80482-A671-447F-BB46-8121D422BD81}">
              <p:d />
            </r>
            <r
              uid="{7FCE1D2B-E077-4A3D-AF80-996014D9B527}">
              <p:d />
            </r>
            <r
              uid="{37DC6908-9973-4BF3-AA1F-616581927F03}"
              p:after="*[1=2]" />
            <r
              uid="{B7906B15-B51F-4DDA-9D56-0D4EDD3DF208}">
              <p:d />
            </r>
            <r
              uid="{9B9C6914-204E-47B8-ABD6-F2712DC7BB72}">
              <p:d />
            </r>
          </d>
        </r>
    - ID: "1e6decbd-039c-43cc-b439-0a198f868334"
      Hint: Featured Story Headline
      Value: "NOV launches premium Pegasus series drill bits for large-diameter applications"
    - ID: "21d62cf8-1209-47b9-a117-2bb93b891dad"
      Hint: Subheading
      Value: "<p>ReedHycalog's new dual-diameter PDC drill bit maximizes ROP, durability, stability, and steerability.</p>"
    - ID: "230a15ec-92fd-4a68-954b-9689bcba0862"
      Hint: Headline
      Value: "NOV launches premium Pegasus series drill bits for large-diameter applications"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220908T194035Z
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: "NOV launches premium Pegasus series drill bits for large-diameter applications"
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: "NOV launches premium Pegasus series drill bits for large-diameter applications"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\lissettegomezandrews
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\lissettegomezandrews
    - ID: "646de4d6-b128-4a3e-8c68-f789869a811b"
      Hint: businessSegments
      Value: "{3A98FB5B-55BC-4332-A107-34A543AC1970}"
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: "NOV launches premium Pegasus series drill bits for large-diameter applications"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "645fcf7a-990a-4833-b889-76f3fce93281"
    - ID: "9992a471-a0b0-471a-9c6b-6e1048c76e00"
      Hint: brands
      Value: "{000D700C-EE86-43DE-B434-E7718D3F6645}"
    - ID: "a1343418-5a51-40de-9488-0efaa22e2042"
      Hint: contentTag
      Value: "{294053F5-3F2B-4F01-A805-2E3CC257571E}"
    - ID: "b0d622b7-156a-4f17-9ce4-4dd213df0302"
      Hint: Date
      Value: 20221031T000000Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "d4ec7ae2-6d57-4ae3-b582-4af2544a7132"
      Hint: Card Image
      Value: |
        <image mediaid="{4009C1DB-287E-4A77-9A43-D79A5C53025D}" cropregion="18,0,1901,1080" ratio="514:295" width="514" height="295" />
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221031T022725Z
    - ID: "f758f02c-54af-42b1-bcd8-1b3f90a174be"
      Hint: Page Image
      Value: |
        <image mediaid="{4009C1DB-287E-4A77-9A43-D79A5C53025D}" cropregion="0,0,1920,1080" ratio="1920:1080" width="1920" height="1080" alt="" hspace="" vspace="" />
