---
ID: "5f2a074d-1723-450a-ac43-5323c2e9c2dd"
Parent: "8dfd8a57-77e4-4e4e-a720-8f569a679339"
Template: "93e4c55d-9fa4-4945-a03a-1565852b0a90"
Path: /sitecore/content/nov/nov/Home/About/News/Phoenix Series Drill Bits for Geothermal Drilling Applications
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "01fd8c23-1b98-4e4b-9f2d-ecf3eb8aad68"
      Hint: businessUnits
      Value: "{0C44BCB4-A6A1-41FD-AB80-08DB189B3A0D}"
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{901672BD-109F-4BA8-9932-A6A9CA1537C0}"
              s:ds=""
              s:par="Enable Autoplay=true&amp;Add Gradient=1&amp;Text Color=white&amp;Wait Time=5000" />
            <r
              uid="{10CEBA25-FC2A-4F84-8760-9B825D4EAF06}"
              s:ds="{24A91DE1-106E-4F64-AEAB-A52016AE33C7}" />
            <r
              uid="{37DC6908-9973-4BF3-AA1F-616581927F03}"
              s:ds="{D184008D-9482-490B-B39A-292AEE8D92D7}"
              s:par="Use Button for Link" />
            <r
              uid="{3A4E7139-50CB-4BD5-AB2E-460BC7CE5AAF}">
              <p:d />
            </r>
            <r
              uid="{4A654B91-13B8-4E86-8A86-869CFE01D42F}"
              p:after="*[1=2]"
              s:ds="{D2049B70-9419-4EC1-B1E8-0469EB71FFF2}"
              s:id="{1012A5A3-5822-4A4F-9B1B-EB13EB6266EE}"
              s:ph="main" />
            <r
              uid="{29B80482-A671-447F-BB46-8121D422BD81}">
              <p:d />
            </r>
            <r
              uid="{97344B92-7C95-4AC5-BA52-015B4E4B60A0}">
              <p:d />
            </r>
            <r
              uid="{7FCE1D2B-E077-4A3D-AF80-996014D9B527}">
              <p:d />
            </r>
            <r
              uid="{B7906B15-B51F-4DDA-9D56-0D4EDD3DF208}">
              <p:d />
            </r>
            <r
              uid="{9B9C6914-204E-47B8-ABD6-F2712DC7BB72}">
              <p:d />
            </r>
          </d>
        </r>
    - ID: "1e6decbd-039c-43cc-b439-0a198f868334"
      Hint: Featured Story Headline
      Value: Phoenix Series Drill Bits for Geothermal Drilling Applications
    - ID: "21d62cf8-1209-47b9-a117-2bb93b891dad"
      Hint: Subheading
      Value: <p>Empowering Sustainable Energy</p>
    - ID: "230a15ec-92fd-4a68-954b-9689bcba0862"
      Hint: Headline
      Value: Phoenix Series Drill Bits for Geothermal Drilling Applications
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200810T214949Z
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: Phoenix Series Drill Bits for Geothermal Drilling Applications
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: Phoenix Series Drill Bits for Geothermal Drilling Applications
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "646de4d6-b128-4a3e-8c68-f789869a811b"
      Hint: businessSegments
      Value: "{3A98FB5B-55BC-4332-A107-34A543AC1970}"
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: Phoenix Series Drill Bits for Geothermal Drilling Applications
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f4d7ac04-3b68-4b16-b29f-13b063f14c19"
    - ID: "a1343418-5a51-40de-9488-0efaa22e2042"
      Hint: contentTag
      Value: "{294053F5-3F2B-4F01-A805-2E3CC257571E}"
    - ID: "b0d622b7-156a-4f17-9ce4-4dd213df0302"
      Hint: Date
      Value: 20200810T000000Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jeremygrzywa
    - ID: "c57e3a44-44b4-496a-9509-dfe938d498d9"
      Hint: Meta Description
      Value: Empowering Sustainable Energy
    - ID: "d4ec7ae2-6d57-4ae3-b582-4af2544a7132"
      Hint: Card Image
      Value: |
        <image mediaid="{6788E58B-628F-4210-BD53-22AF1512CE7B}" cropregion="18,0,1901,1080" ratio="514:295" width="514" height="295" />
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200819T142915Z
    - ID: "f758f02c-54af-42b1-bcd8-1b3f90a174be"
      Hint: Page Image
      Value: |
        <image mediaid="{6788E58B-628F-4210-BD53-22AF1512CE7B}" cropregion="0,0,1920,1080" ratio="1920:1080" width="1920" height="1080" />
