---
ID: "734f93d4-7891-48d7-b963-cf1073809049"
Parent: "447b01de-b691-4983-b4a7-1e03dff32250"
Template: "dbc23d7d-62bd-46a5-b584-58b43c5dfaad"
Path: /sitecore/content/nov/nov/Home/Products
SharedFields:
- ID: "66afdd9e-0c87-4ef2-9ef2-405f3b88a047"
  Hint: Hide From Search
  Value: 1
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "1e6decbd-039c-43cc-b439-0a198f868334"
      Hint: Featured Story Headline
      Value: Products
    - ID: "20bea456-514e-4310-b4ef-0a14480840c1"
      Hint: Hide Secondary Navigation
      Value: 1
    - ID: "230a15ec-92fd-4a68-954b-9689bcba0862"
      Hint: Headline
      Value: Products
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190903T211708Z
    - ID: "351936cd-20a5-40f7-8175-c4d224afadab"
      Hint: Hide In Navigation
      Value: 1
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: Products
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: Products
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: Products
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d73dfc88-ff29-4fea-96a5-c47227342371"
    - ID: "8e5f2089-9c97-40f6-863a-9a9ce9fac0dc"
      Hint: redirectPageName
      Value: Products and Services
    - ID: "926f1875-e20e-41cb-a705-e45affa0dc35"
      Hint: redirectPageURL
      Value: |
        <link linktype="internal" querystring="" target="" id="{4113E0AF-27A5-4EFC-86BA-EE320DFA4C5E}" />
    - ID: "a1343418-5a51-40de-9488-0efaa22e2042"
      Hint: contentTag
      Value: "{97803E00-415E-418E-BD59-EC82DC5F73D8}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190903T211856Z
