---
ID: "6485f1cb-bb27-4252-8e8a-97e7128cd19c"
Parent: "4e5d2812-fa3c-49a0-bdc9-e78174c92c21"
Template: "4e5d2812-fa3c-49a0-bdc9-e78174c92c21"
Path: /sitecore/templates/Feature/NOV Shared/Field Sections/Cropped Image Fields/Optional/Image 1280x1080/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190121T183035Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "37c5a18f-55c5-44d2-8814-228c77f2d4c2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190121T183035Z
