---
ID: "85a79044-5094-4a55-819c-9b101358126d"
Parent: "ca04b9e8-cf66-48cb-8807-5a8c1fe925d1"
Template: "ca04b9e8-cf66-48cb-8807-5a8c1fe925d1"
Path: /sitecore/templates/Feature/NOV Com/Modules/Search Modules/Search Form/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181103T222302Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d56716e6-9353-4301-9643-3515dafc102e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20191009T181956Z
