---
ID: "dc4aa687-39da-47ff-956e-1234965c3cca"
Parent: "98e7b308-74a7-4dc4-9fb9-ecd33115449c"
Template: "5c70ee4b-1d66-41d1-a671-1cd882733bf5"
Path: /sitecore/content/nov/nov/Data/Modules/Products/CAPS/Intervention and Stimulation Equipment/Condition Based Maintenance CBM System/CBM for Coiled Tubing Applications/CBM for Coiled Tubing Applications
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190425T115827Z
    - ID: "3bb32c55-8204-4e4c-bc91-26197822ead5"
      Hint: image
      Value: |
        <image mediaid="{9EEEF795-FD90-45B9-B62F-5BBB0F1DC6A4}" cropregion="0,172,1920,1252" ratio="1920:1080" width="1920" height="1080" />
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "492cda75-be72-41de-b849-77bf42bda182"
      Hint: contenttag
      Value: "{1F7E6CF6-397F-43E3-8BE0-F22A71E03F76}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\verticljensen
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\verticljensen
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e9bbe5a0-833f-43bf-b91f-a5ecacf3705c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\verticljensen
    - ID: "c722b334-9504-41e1-bcf9-d58e5646dd0c"
      Hint: subheading
      Value: "<p>The CTES&trade; condition-based maintenance (CBM) system is a custom real-time monitoring system for your intervention and stimulation equipment. This system is designed to improve uptime and reduce maintenance costs associated with personnel and inventory requirements through early identification of potential failures.</p>"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190425T120023Z
    - ID: "fe09ae44-5f98-442e-9b46-c524724c0c38"
      Hint: heading
      Value: CBM for Coiled Tubing Applications
  - Version: 2
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190425T124842Z
    - ID: "3bb32c55-8204-4e4c-bc91-26197822ead5"
      Hint: image
      Value: |
        <image mediaid="{9EEEF795-FD90-45B9-B62F-5BBB0F1DC6A4}" cropregion="0,172,1920,1252" ratio="1920:1080" width="1920" height="1080" />
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "492cda75-be72-41de-b849-77bf42bda182"
      Hint: contenttag
      Value: "{1F7E6CF6-397F-43E3-8BE0-F22A71E03F76}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\verticljensen
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\verticljensen
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a8cae7e2-0b9f-468d-b64a-c8c22f7a35d2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\verticljensen
    - ID: "c722b334-9504-41e1-bcf9-d58e5646dd0c"
      Hint: subheading
      Value: "<p>The CTES&trade; condition-based maintenance (CBM) system is a custom real-time monitoring system for your intervention and stimulation equipment. This system is designed to improve uptime and reduce maintenance costs associated with personnel and inventory requirements through early identification of potential failures.</p>"
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20190425T124842Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190425T124855Z
    - ID: "fe09ae44-5f98-442e-9b46-c524724c0c38"
      Hint: heading
      Value: CBM for Coiled Tubing Applications
  - Version: 3
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190510T112434Z
    - ID: "3bb32c55-8204-4e4c-bc91-26197822ead5"
      Hint: image
      Value: |
        <image mediaid="{9EEEF795-FD90-45B9-B62F-5BBB0F1DC6A4}" cropregion="0,172,1920,1252" ratio="1920:1080" width="1920" height="1080" />
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "492cda75-be72-41de-b849-77bf42bda182"
      Hint: contenttag
      Value: "{1F7E6CF6-397F-43E3-8BE0-F22A71E03F76}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\verticljensen
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\verticljensen
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "39c1bf5b-b458-438e-9320-9405079c3ed6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\heatherbaxter
    - ID: "c722b334-9504-41e1-bcf9-d58e5646dd0c"
      Hint: subheading
      Value: "<p>Our CTES condition-based maintenance system improves uptime and reduces maintenance costs by monitoring your intervention and stimulation equipment in real time.</p>"
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20190510T112434Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190514T132919Z
    - ID: "fe09ae44-5f98-442e-9b46-c524724c0c38"
      Hint: heading
      Value: CBM for Coiled Tubing Applications
