---
ID: "b182f4ef-7c07-428f-abac-2356fc1fe4e1"
Parent: "e0ae98ad-d091-4c4a-b089-0cb1640e7a04"
Template: "e0ae98ad-d091-4c4a-b089-0cb1640e7a04"
Path: /sitecore/templates/Feature/NOV Com/Modules/Hero Modules/Home Page Hero/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180921T144224Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e84386c1-331f-4f43-a5f5-09468929f6ef"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181004T192055Z
