---
ID: "5c7177ab-cbcd-4063-bc9d-850aa55f172e"
Parent: "5a168976-0531-4001-ad78-e76eeb5184af"
Template: "2a8117d9-ebd1-430b-abd4-1d33b1fee79c"
Path: /sitecore/content/nov/nov/Data/Modules/Products/CAPS/Process and Flow Technologies/Choke Automation/Production Choke Automation E5 Document List
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190826T145516Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\melissapastrano
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\melissapastrano
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c5e85a37-7366-4d88-8e0a-9c8d70eb2e73"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\adminrschuhsler
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200513T195914Z
    - ID: "e4424681-e459-4738-a286-2240e08da75e"
      Hint: assets
      Value: "{7495EAF7-381C-43D7-BA57-EC6EEB319F4F}"
