---
ID: "1bb2708c-1486-4642-bd07-cb532132eca6"
Parent: "5a168976-0531-4001-ad78-e76eeb5184af"
Template: "c0aa2bad-85b9-47e4-a236-901c3115fb87"
Path: /sitecore/content/nov/nov/Data/Modules/Products/CAPS/Process and Flow Technologies/Choke Automation/Production Choke Automation J5 Features List
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190826T145118Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "4d669ee9-9ff5-4c31-a025-56035d1727a1"
      Hint: column1Headline
      Value: Features/Benefits
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\melissapastrano
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\melissapastrano
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "60b53c5e-2a18-4e4f-90e8-b68fb44aa349"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\adminrschuhsler
    - ID: "c3afee16-1dbc-4a49-8037-9d03d0d7d62e"
      Hint: description
      Value: |
        <p><span lang="EN-GB">Our manual chokes are designed with future automation in mind. These models can be converted to automated operations in a simple, efficient, and economical manner. Chokes can be fitted with multiple types of actuators based on customer preference. &nbsp;</span></p>
        <p><span lang="EN-GB">In some cases, it may be necessary to replace the choke bonnet and stem to accommodate some manufacturers’ actuator models. We provide a fully engineered and preassembled bonnet assembly as a complete automation upgrade kit, keeping your downtime for the conversion to an absolute minimum.</span></p>
        <p><strong><span lang="EN-GB">Position control and measurement</span></strong></p>
        <p><span lang="EN-GB">Reliable process control depends on accurate and repeatable positioning of the choke throughout its range of operation. Various control and position feedback options are available with electrical components certified for use in hazardous areas. FM/UL Class I, Div 1, CSA, ATEX EExd, and EExia chokes are available. We can also provide an interface to major international standards communication and control protocols such as Foundation Fieldbus, Profibus, Device Net, Modbus, and HART.</span></p>
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200513T195914Z
    - ID: "f6afec27-750a-4d77-962d-3ce002b623b9"
      Hint: column1List
      Value: |
        <ul>
            <li>Pneumatic supply at 80 to 120 psi maximum</li>
            <li>Hydraulic supply at 1,500 to 3,000 psi maximum</li>
            <li>Visual position indicator</li>
            <li>Manual override via hex shaft</li>
            <li>Fail-safe last position</li>
            <li>Watertight housing with corrosion-resistant coating</li>
            <li>Wiring junction box</li>
            <li>Field tested</li>
        </ul>
