---
ID: "745cdc7a-d570-4330-8708-4e9857b9b24a"
Parent: "e117af57-6a17-46c6-8a26-5852331bcf35"
Template: "c0aa2bad-85b9-47e4-a236-901c3115fb87"
Path: /sitecore/content/nov/nov/Data/Modules/Products/WBT/WellSite Services/Water Filtration Applications/Water Filtration Applications J5 Features List
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190314T141948Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\charisgamroth
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\charisgamroth
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2c3ec46e-9080-4e65-9388-7768375696de"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\charisgamroth
    - ID: "c3afee16-1dbc-4a49-8037-9d03d0d7d62e"
      Hint: description
      Value: |
        <p>We offer a variety of treatment and filtration solutions, including filtration pods (with both absolute and nominal filters); coalescing, cartridge, bag, and spiral-wound filtration options; membrane solutions; horizontal and vertical diatomaceous earth (DE) presses; the Aqua-VES&trade; offshore slops unit; and a variety of chemical-based treatment solutions. Chemical offerings include biocide treatment; iron, scale, and corrosion inhibitors; de-emulsifiers, wetting agents, and surfactants; hydrogen sulfide treatment; oxidizing agents; antifreeze solutions; water softening/chemical precipitation; and flocculants.</p>
        <p>Our NOV Water Services group is equipped to offer tailor-made solutions for a variety of frac fluids, flowback and produced water, slops, and waste water applications.</p>
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190314T142254Z
