---
ID: "f7ec6b0d-534f-4bfb-959b-26c28e67f885"
Parent: "74eafb5e-8412-4733-a701-8e9c998f307c"
Template: "d227ab0e-fd44-4ae0-878a-189949913d0b"
Path: /sitecore/content/nov/nov/Home/About/Sustainability/Environmental
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{B0614C31-68EB-476B-A1C4-505C4E06F703}"
              p:before="*"
              s:ds="{ADFF4D7C-98F9-4342-83E6-DAD526BB3799}"
              s:id="{EAEFE2D3-091C-438E-9B07-903F732D1754}"
              s:par="Alignment=left"
              s:ph="/main/sidebar-content" />
            <r
              uid="{C4ACEA35-73C2-4347-B325-2FC6FCDAAB8F}">
              <p:d />
            </r>
            <r
              uid="{CC26DA26-1B03-4216-888B-D5040492EE38}"
              p:after="r[@uid='{83C96A38-D18A-4E35-9D8D-71F869B259F3}']"
              s:ds="{E2D4BBA8-5047-4A8E-A9D0-7DDCF6EB292B}"
              s:id="{A22722F6-65DF-4574-B659-191957028C9B}"
              s:par=""
              s:ph="main" />
            <r
              uid="{E655A92B-3794-4099-AF60-076BAFA33189}">
              <p:d />
            </r>
            <r
              uid="{1FD9ED8E-765E-4D75-AEB7-9C5643309FB1}">
              <p:d />
            </r>
            <r
              uid="{C3E128BD-C527-476C-B850-4FF98996AE1F}">
              <p:d />
            </r>
            <r
              uid="{9E4C6427-3865-4F4C-AF91-EFDF6A58DA77}">
              <p:d />
            </r>
            <r
              uid="{ACAD23C8-9219-4D65-B38A-4537A73C4FE0}">
              <p:d />
            </r>
            <r
              uid="{FB4C5C8E-DF5F-4300-950E-536065A8707B}"
              s:ds="{01FF6BF5-FE88-4EE1-B7E1-2D7982F456A2}" />
            <r
              uid="{2849CE03-88F2-4FBC-BAE4-0D1B29D7AEAA}">
              <p:d />
            </r>
            <r
              uid="{B5407315-4598-49BA-A716-8895E8E1539E}">
              <p:d />
            </r>
            <r
              uid="{35F5B041-CCEA-40B8-948D-6DE09851A28E}">
              <p:d />
            </r>
            <r
              uid="{291AE356-4688-44A8-A2DC-E0249B1A5E25}"
              p:after="r[@uid='{FB4C5C8E-DF5F-4300-950E-536065A8707B}']"
              s:ds="{A71C93FC-9315-4D21-8656-CE36CD70E0B6}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=left&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{BC7C90FA-0379-4509-8D9B-064CE7259B8B}"
              p:after="r[@uid='{291AE356-4688-44A8-A2DC-E0249B1A5E25}']"
              s:ds="{DE2C6C1D-4654-460A-B1EE-9A3C6A24B228}"
              s:id="{410308FD-D76D-48D4-9E14-E9C56F2AECDF}"
              s:ph="main" />
            <r
              uid="{0D97EC48-A616-4503-81F3-8B0A22142C87}"
              p:after="*[1=2]"
              s:ds="{71ADA884-2C21-439E-8B2C-80115D7692B3}" />
            <r
              uid="{99B4E79C-EEB8-49BC-8779-24C4AD0CF113}">
              <p:d />
            </r>
            <r
              uid="{CDF8E396-F69A-48ED-A6DB-B665BD98B242}">
              <p:d />
            </r>
            <r
              uid="{3ADDDF2A-6C4B-4473-ACB2-EADC8ABD6475}">
              <p:d />
            </r>
            <r
              uid="{8036035A-E577-44BC-A961-631ADBC08C0F}">
              <p:d />
            </r>
          </d>
        </r>
    - ID: "1e6decbd-039c-43cc-b439-0a198f868334"
      Hint: Featured Story Headline
      Value: ESG | Environmental
    - ID: "21d62cf8-1209-47b9-a117-2bb93b891dad"
      Hint: Subheading
      Value: <p>We provide technologies, products, and services that enable our customers and facilities to operate in a compliant and environmentally conscious manner. </p>
    - ID: "230a15ec-92fd-4a68-954b-9689bcba0862"
      Hint: Headline
      Value: ESG | Environmental
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201008T183212Z
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: Environmental
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: ESG | Environmental
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: Environmental
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "53c75275-0c76-48fc-bfa6-e6c9b2910390"
    - ID: "a1343418-5a51-40de-9488-0efaa22e2042"
      Hint: contentTag
      Value: "{97803E00-415E-418E-BD59-EC82DC5F73D8}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "c57e3a44-44b4-496a-9509-dfe938d498d9"
      Hint: Meta Description
      Value: We provide technologies, products, and services that enable our customers and facilities to operate in a compliant and environmentally conscious manner. 
    - ID: "d4ec7ae2-6d57-4ae3-b582-4af2544a7132"
      Hint: Card Image
      Value: |
        <image mediaid="{080CA72C-F5E1-49A3-A929-B2F32C4EA26D}" cropregion="18,0,1901,1080" ratio="514:295" width="514" height="295" />
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220411T181008Z
    - ID: "f758f02c-54af-42b1-bcd8-1b3f90a174be"
      Hint: Page Image
      Value: |
        <image mediaid="{080CA72C-F5E1-49A3-A929-B2F32C4EA26D}" cropregion="0,0,1920,1080" ratio="1920:1080" width="1920" height="1080" />
  - Version: 2
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "019c3c8b-3d47-4b92-a8e9-838880ddf307"
      Hint: Open Graph Title
      Value: Environmental
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{B0614C31-68EB-476B-A1C4-505C4E06F703}"
              p:before="*"
              s:ds="{ADFF4D7C-98F9-4342-83E6-DAD526BB3799}"
              s:id="{EAEFE2D3-091C-438E-9B07-903F732D1754}"
              s:par="Alignment=left"
              s:ph="/main/sidebar-content" />
            <r
              uid="{C4ACEA35-73C2-4347-B325-2FC6FCDAAB8F}">
              <p:d />
            </r>
            <r
              uid="{CC26DA26-1B03-4216-888B-D5040492EE38}"
              p:after="r[@uid='{83C96A38-D18A-4E35-9D8D-71F869B259F3}']"
              s:ds="{E2D4BBA8-5047-4A8E-A9D0-7DDCF6EB292B}"
              s:id="{A22722F6-65DF-4574-B659-191957028C9B}"
              s:par=""
              s:ph="main" />
            <r
              uid="{E655A92B-3794-4099-AF60-076BAFA33189}">
              <p:d />
            </r>
            <r
              uid="{1FD9ED8E-765E-4D75-AEB7-9C5643309FB1}">
              <p:d />
            </r>
            <r
              uid="{C3E128BD-C527-476C-B850-4FF98996AE1F}">
              <p:d />
            </r>
            <r
              uid="{9E4C6427-3865-4F4C-AF91-EFDF6A58DA77}">
              <p:d />
            </r>
            <r
              uid="{ACAD23C8-9219-4D65-B38A-4537A73C4FE0}">
              <p:d />
            </r>
            <r
              uid="{FB4C5C8E-DF5F-4300-950E-536065A8707B}"
              s:ds="{01FF6BF5-FE88-4EE1-B7E1-2D7982F456A2}" />
            <r
              uid="{2849CE03-88F2-4FBC-BAE4-0D1B29D7AEAA}">
              <p:d />
            </r>
            <r
              uid="{B5407315-4598-49BA-A716-8895E8E1539E}">
              <p:d />
            </r>
            <r
              uid="{35F5B041-CCEA-40B8-948D-6DE09851A28E}">
              <p:d />
            </r>
            <r
              uid="{291AE356-4688-44A8-A2DC-E0249B1A5E25}"
              p:after="r[@uid='{FB4C5C8E-DF5F-4300-950E-536065A8707B}']"
              s:ds="{A71C93FC-9315-4D21-8656-CE36CD70E0B6}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=left&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{1DA2B909-6EC5-40F9-9BC8-CD6488CD3D40}"
              p:after="r[@uid='{291AE356-4688-44A8-A2DC-E0249B1A5E25}']"
              s:ds="{B2EC566C-2628-434C-8FE1-0E1A0871CD0C}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=right&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{0D97EC48-A616-4503-81F3-8B0A22142C87}"
              p:after="*[1=2]"
              s:ds="{71ADA884-2C21-439E-8B2C-80115D7692B3}" />
            <r
              uid="{99B4E79C-EEB8-49BC-8779-24C4AD0CF113}">
              <p:d />
            </r>
            <r
              uid="{CDF8E396-F69A-48ED-A6DB-B665BD98B242}">
              <p:d />
            </r>
            <r
              uid="{3ADDDF2A-6C4B-4473-ACB2-EADC8ABD6475}">
              <p:d />
            </r>
            <r
              uid="{8036035A-E577-44BC-A961-631ADBC08C0F}">
              <p:d />
            </r>
          </d>
        </r>
    - ID: "1e6decbd-039c-43cc-b439-0a198f868334"
      Hint: Featured Story Headline
      Value: ESG | Environmental
    - ID: "21d62cf8-1209-47b9-a117-2bb93b891dad"
      Hint: Subheading
      Value: <p>By being intentional in developing products and processes that are both environmentally conscious and compliant with local rules and regulations we can limit the environmental impact of our customers' and our own operations.</p>
    - ID: "230a15ec-92fd-4a68-954b-9689bcba0862"
      Hint: Headline
      Value: ESG | Environmental
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220617T033243Z
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: Environmental
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: ESG | Environmental
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "586cb512-0fa1-42f0-ab48-d3e399853ca8"
      Hint: Open Graph Image
      Value: |
        <image mediaid="{2E8764C0-B1FF-42BB-9EC2-3FEAE3D30EB4}" />
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\lissettegomezandrews
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: Environmental
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5fc68be1-7fe2-49ef-a0ac-7ad6217b8734"
    - ID: "a1343418-5a51-40de-9488-0efaa22e2042"
      Hint: contentTag
      Value: "{97803E00-415E-418E-BD59-EC82DC5F73D8}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\lissettegomezandrews
    - ID: "c57e3a44-44b4-496a-9509-dfe938d498d9"
      Hint: Meta Description
      Value: We provide technologies, products, and services that enable our customers and facilities to operate in a compliant and environmentally conscious manner. 
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20220617T033243Z
    - ID: "d4ec7ae2-6d57-4ae3-b582-4af2544a7132"
      Hint: Card Image
      Value: |
        <image mediaid="{502DD8BE-461C-4C67-AB84-AF1EC80D6CC0}" cropregion="0,16,1920,1119" ratio="514:295" width="514" height="295" />
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220812T183136Z
    - ID: "f758f02c-54af-42b1-bcd8-1b3f90a174be"
      Hint: Page Image
      Value: |
        <image mediaid="{502DD8BE-461C-4C67-AB84-AF1EC80D6CC0}" cropregion="0,28,1920,1108" ratio="1920:1080" width="1920" height="1080" />
  - Version: 3
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "019c3c8b-3d47-4b92-a8e9-838880ddf307"
      Hint: Open Graph Title
      Value: Environmental
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{B0614C31-68EB-476B-A1C4-505C4E06F703}"
              p:before="*"
              s:ds="{ADFF4D7C-98F9-4342-83E6-DAD526BB3799}"
              s:id="{EAEFE2D3-091C-438E-9B07-903F732D1754}"
              s:par="Alignment=left"
              s:ph="/main/sidebar-content" />
            <r
              uid="{C4ACEA35-73C2-4347-B325-2FC6FCDAAB8F}">
              <p:d />
            </r>
            <r
              uid="{CC26DA26-1B03-4216-888B-D5040492EE38}"
              p:after="r[@uid='{83C96A38-D18A-4E35-9D8D-71F869B259F3}']"
              s:ds="{E2D4BBA8-5047-4A8E-A9D0-7DDCF6EB292B}"
              s:id="{A22722F6-65DF-4574-B659-191957028C9B}"
              s:par=""
              s:ph="main" />
            <r
              uid="{E655A92B-3794-4099-AF60-076BAFA33189}">
              <p:d />
            </r>
            <r
              uid="{1FD9ED8E-765E-4D75-AEB7-9C5643309FB1}">
              <p:d />
            </r>
            <r
              uid="{C3E128BD-C527-476C-B850-4FF98996AE1F}">
              <p:d />
            </r>
            <r
              uid="{9E4C6427-3865-4F4C-AF91-EFDF6A58DA77}">
              <p:d />
            </r>
            <r
              uid="{ACAD23C8-9219-4D65-B38A-4537A73C4FE0}">
              <p:d />
            </r>
            <r
              uid="{FB4C5C8E-DF5F-4300-950E-536065A8707B}"
              s:ds="{01FF6BF5-FE88-4EE1-B7E1-2D7982F456A2}" />
            <r
              uid="{2849CE03-88F2-4FBC-BAE4-0D1B29D7AEAA}">
              <p:d />
            </r>
            <r
              uid="{B5407315-4598-49BA-A716-8895E8E1539E}">
              <p:d />
            </r>
            <r
              uid="{35F5B041-CCEA-40B8-948D-6DE09851A28E}">
              <p:d />
            </r>
            <r
              uid="{291AE356-4688-44A8-A2DC-E0249B1A5E25}"
              p:after="r[@uid='{FB4C5C8E-DF5F-4300-950E-536065A8707B}']"
              s:ds="{A71C93FC-9315-4D21-8656-CE36CD70E0B6}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=left&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{1DA2B909-6EC5-40F9-9BC8-CD6488CD3D40}"
              p:after="r[@uid='{291AE356-4688-44A8-A2DC-E0249B1A5E25}']"
              s:ds="{B2EC566C-2628-434C-8FE1-0E1A0871CD0C}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=right&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{0D97EC48-A616-4503-81F3-8B0A22142C87}"
              p:after="*[1=2]"
              s:ds="{71ADA884-2C21-439E-8B2C-80115D7692B3}" />
            <r
              uid="{99B4E79C-EEB8-49BC-8779-24C4AD0CF113}">
              <p:d />
            </r>
            <r
              uid="{CDF8E396-F69A-48ED-A6DB-B665BD98B242}">
              <p:d />
            </r>
            <r
              uid="{3ADDDF2A-6C4B-4473-ACB2-EADC8ABD6475}">
              <p:d />
            </r>
            <r
              uid="{8036035A-E577-44BC-A961-631ADBC08C0F}">
              <p:d />
            </r>
          </d>
        </r>
    - ID: "1e6decbd-039c-43cc-b439-0a198f868334"
      Hint: Featured Story Headline
      Value: ESG | Environmental
    - ID: "21d62cf8-1209-47b9-a117-2bb93b891dad"
      Hint: Subheading
      Value: <p>By being intentional in developing products and processes that are both environmentally conscious and compliant with local rules and regulations we can limit the environmental impact of our customers' and our own operations.</p>
    - ID: "230a15ec-92fd-4a68-954b-9689bcba0862"
      Hint: Headline
      Value: ESG | Environmental
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230406T145519Z
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: Environmental
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: ESG | Environmental
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "586cb512-0fa1-42f0-ab48-d3e399853ca8"
      Hint: Open Graph Image
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\lissettegomezandrews
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: Environmental
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eebd945a-aee5-4998-b179-c90d8d0d02b8"
    - ID: "a1343418-5a51-40de-9488-0efaa22e2042"
      Hint: contentTag
      Value: "{97803E00-415E-418E-BD59-EC82DC5F73D8}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\lissettegomezandrews
    - ID: "c57e3a44-44b4-496a-9509-dfe938d498d9"
      Hint: Meta Description
      Value: We provide technologies, products, and services that enable our customers and facilities to operate in a compliant and environmentally conscious manner. 
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20230406T145519Z
    - ID: "d4ec7ae2-6d57-4ae3-b582-4af2544a7132"
      Hint: Card Image
      Value: |
        <image mediaid="{83D472C5-74A2-4F99-8B4B-024972C0A5D1}" cropregion="20,0,1902,1080" ratio="514:295" width="514" height="295" />
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230406T173053Z
    - ID: "f758f02c-54af-42b1-bcd8-1b3f90a174be"
      Hint: Page Image
      Value: |
        <image mediaid="{83D472C5-74A2-4F99-8B4B-024972C0A5D1}" cropregion="1,0,1921,1080" ratio="1920:1080" width="1920" height="1080" />
