---
ID: "87ace156-0eca-4509-8583-cb650928fb7e"
Parent: "4113e0af-27a5-4efc-86ba-ee320dfa4c5e"
Template: "dbc23d7d-62bd-46a5-b584-58b43c5dfaad"
Path: /sitecore/content/nov/nov/Home/Products and Services/Training
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "1e6decbd-039c-43cc-b439-0a198f868334"
      Hint: Featured Story Headline
      Value: Training
    - ID: "21d62cf8-1209-47b9-a117-2bb93b891dad"
      Hint: Subheading
      Value: |
        <p>NOV Training Centers are the only training centers that can guarantee up-to-date OEM training on NOV products and equipment.</p>
        <br />
    - ID: "230a15ec-92fd-4a68-954b-9689bcba0862"
      Hint: Headline
      Value: Training
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190521T131616Z
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: Training
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: Training
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kaileyshelton
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kaileyshelton
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: Training
    - ID: "7c2c7685-a8a6-4130-86ae-102efa679725"
      Hint: Featured Story Abstract
      Value: "NOV Training Centers are the only training centers that can guarantee up-to-date OEM training on NOV products and equipment."
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b424eade-62fb-4f9a-a0da-0d42eed932c9"
    - ID: "8e5f2089-9c97-40f6-863a-9a9ce9fac0dc"
      Hint: redirectPageName
      Value: Training
    - ID: "926f1875-e20e-41cb-a705-e45affa0dc35"
      Hint: redirectPageURL
      Value: |
        <link text="www.nov.com/training" linktype="external" url="" anchor="" target="" />
    - ID: "a1343418-5a51-40de-9488-0efaa22e2042"
      Hint: contentTag
      Value: "{1801C7F9-21C1-4DBE-8DD6-55E04DBA8546}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kaileyshelton
    - ID: "d4ec7ae2-6d57-4ae3-b582-4af2544a7132"
      Hint: Card Image
      Value: |
        <image mediaid="{C57031E2-CDDC-44F6-85E2-A9E47A905190}" cropregion="0,883,1427,1702" ratio="514:295" width="514" height="295" alt="" hspace="" vspace="" />
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190521T132508Z
    - ID: "f758f02c-54af-42b1-bcd8-1b3f90a174be"
      Hint: Page Image
      Value: |
        <image mediaid="{C57031E2-CDDC-44F6-85E2-A9E47A905190}" cropregion="6,922,1427,1715" ratio="1920:1080" width="1920" height="1080" alt="" hspace="" vspace="" />
  - Version: 2
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "1e6decbd-039c-43cc-b439-0a198f868334"
      Hint: Featured Story Headline
      Value: Training
    - ID: "21d62cf8-1209-47b9-a117-2bb93b891dad"
      Hint: Subheading
      Value: |
        <p>NOV Training Centers are the only training centers that can guarantee up-to-date OEM training on NOV products and equipment.</p>
        <br />
    - ID: "230a15ec-92fd-4a68-954b-9689bcba0862"
      Hint: Headline
      Value: Training
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190607T195156Z
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: Training
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: Training
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kaileyshelton
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\charisgamroth
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: Training
    - ID: "7c2c7685-a8a6-4130-86ae-102efa679725"
      Hint: Featured Story Abstract
      Value: "NOV Training Centers are the only training centers that can guarantee up-to-date OEM training on NOV products and equipment."
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8303dfd7-d37a-4f21-983d-500809a8381d"
    - ID: "8e5f2089-9c97-40f6-863a-9a9ce9fac0dc"
      Hint: redirectPageName
      Value: Training
    - ID: "926f1875-e20e-41cb-a705-e45affa0dc35"
      Hint: redirectPageURL
      Value: |
        <link text="www.nov.com/training" linktype="external" url="http://www.nov.com/training" anchor="" target="" />
    - ID: "a1343418-5a51-40de-9488-0efaa22e2042"
      Hint: contentTag
      Value: "{1801C7F9-21C1-4DBE-8DD6-55E04DBA8546}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\charisgamroth
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20190607T195156Z
    - ID: "d4ec7ae2-6d57-4ae3-b582-4af2544a7132"
      Hint: Card Image
      Value: |
        <image mediaid="{C57031E2-CDDC-44F6-85E2-A9E47A905190}" cropregion="0,883,1427,1702" ratio="514:295" width="514" height="295" alt="" hspace="" vspace="" />
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190607T195303Z
    - ID: "f758f02c-54af-42b1-bcd8-1b3f90a174be"
      Hint: Page Image
      Value: |
        <image mediaid="{C57031E2-CDDC-44F6-85E2-A9E47A905190}" cropregion="6,922,1427,1715" ratio="1920:1080" width="1920" height="1080" alt="" hspace="" vspace="" />
  - Version: 3
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "1e6decbd-039c-43cc-b439-0a198f868334"
      Hint: Featured Story Headline
      Value: Training
    - ID: "21d62cf8-1209-47b9-a117-2bb93b891dad"
      Hint: Subheading
      Value: |
        <p>NOV Training Centers are the only training centers that can guarantee up-to-date OEM training on NOV products and equipment.</p>
        <br />
    - ID: "230a15ec-92fd-4a68-954b-9689bcba0862"
      Hint: Headline
      Value: Training
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190709T181038Z
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: Training
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: Training
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kaileyshelton
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\charisgamroth
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: Training
    - ID: "7c2c7685-a8a6-4130-86ae-102efa679725"
      Hint: Featured Story Abstract
      Value: "NOV Training Centers are the only training centers that can guarantee up-to-date OEM training on NOV products and equipment."
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "81279b13-5b96-4c14-8133-272258dae36e"
    - ID: "8e5f2089-9c97-40f6-863a-9a9ce9fac0dc"
      Hint: redirectPageName
      Value: Training
    - ID: "926f1875-e20e-41cb-a705-e45affa0dc35"
      Hint: redirectPageURL
      Value: |
        <link text="www.nov.com/training" linktype="external" url="http://www.nov.com/training" anchor="" target="" />
    - ID: "a1343418-5a51-40de-9488-0efaa22e2042"
      Hint: contentTag
      Value: "{1801C7F9-21C1-4DBE-8DD6-55E04DBA8546}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\charisgamroth
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20190709T181038Z
    - ID: "d4ec7ae2-6d57-4ae3-b582-4af2544a7132"
      Hint: Card Image
      Value: |
        <image mediaid="{90F60534-753F-4446-95C5-427FA6498EDA}" cropregion="18,0,1901,1080" ratio="514:295" width="514" height="295" alt="" hspace="" vspace="" />
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190709T191631Z
    - ID: "f758f02c-54af-42b1-bcd8-1b3f90a174be"
      Hint: Page Image
      Value: |
        <image mediaid="{90F60534-753F-4446-95C5-427FA6498EDA}" cropregion="0,0,1920,1080" ratio="1920:1080" width="1920" height="1080" alt="" hspace="" vspace="" />
  - Version: 4
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "1e6decbd-039c-43cc-b439-0a198f868334"
      Hint: Featured Story Headline
      Value: Training
    - ID: "21d62cf8-1209-47b9-a117-2bb93b891dad"
      Hint: Subheading
      Value: |
        <p>NOV Training Centers are the only training centers that can guarantee up-to-date OEM training on NOV products and equipment.</p>
        <br />
    - ID: "230a15ec-92fd-4a68-954b-9689bcba0862"
      Hint: Headline
      Value: Training
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220812T195957Z
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: Training
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: Training
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kaileyshelton
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\lissettegomezandrews
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: Training
    - ID: "7c2c7685-a8a6-4130-86ae-102efa679725"
      Hint: Featured Story Abstract
      Value: "NOV Training Centers are the only training centers that can guarantee up-to-date OEM training on NOV products and equipment."
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6b8f1873-a1f3-4c66-8c86-21d94898dc88"
    - ID: "8e5f2089-9c97-40f6-863a-9a9ce9fac0dc"
      Hint: redirectPageName
      Value: Training
    - ID: "926f1875-e20e-41cb-a705-e45affa0dc35"
      Hint: redirectPageURL
      Value: |
        <link linktype="external" url="https://training.nov.com/" anchor="" target="" />
    - ID: "a1343418-5a51-40de-9488-0efaa22e2042"
      Hint: contentTag
      Value: "{1801C7F9-21C1-4DBE-8DD6-55E04DBA8546}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\lissettegomezandrews
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20220812T195957Z
    - ID: "d4ec7ae2-6d57-4ae3-b582-4af2544a7132"
      Hint: Card Image
      Value: |
        <image mediaid="{90F60534-753F-4446-95C5-427FA6498EDA}" cropregion="18,0,1901,1080" ratio="514:295" width="514" height="295" alt="" hspace="" vspace="" />
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220812T200059Z
    - ID: "f758f02c-54af-42b1-bcd8-1b3f90a174be"
      Hint: Page Image
      Value: |
        <image mediaid="{90F60534-753F-4446-95C5-427FA6498EDA}" cropregion="0,0,1920,1080" ratio="1920:1080" width="1920" height="1080" alt="" hspace="" vspace="" />
