---
ID: "3dfaecb3-7b78-489d-8875-72f1f6765074"
Parent: "94f4ea07-6852-450b-9418-50b7c0fffe4b"
Template: "94f4ea07-6852-450b-9418-50b7c0fffe4b"
Path: /sitecore/templates/Project/nov/NOV Shared/Components/Asset Type/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181024T172856Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "da1eceb9-9168-4efc-8bc3-c4254e0c9138"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181024T172856Z
