---
ID: "d384a77c-0a47-4f6a-9d0a-6f77ab7785c1"
Parent: "a3683aaa-e58e-4f01-8514-bce0fb6b9bbb"
Template: "a3683aaa-e58e-4f01-8514-bce0fb6b9bbb"
Path: /sitecore/templates/Feature/NOV Shared/Field Sections/Cropped Image Fields/Required/Image 393x600 Required/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190121T182455Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "097d0215-68c6-43ae-8896-3cab20c39541"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190121T182455Z
