---
ID: "57fab1c3-b4c9-4b59-99b5-94979fb5c544"
Parent: "73bf5ace-e4cd-4a65-bf99-61a6f26c0d44"
Template: "73bf5ace-e4cd-4a65-bf99-61a6f26c0d44"
Path: /sitecore/templates/Feature/NOV Com/Modules/Product/Sticky Button/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181101T184035Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3b9f1082-37fd-4851-b530-01b4de484b82"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181101T184035Z
