---
ID: "930f723a-fdde-4e55-b908-3f6b39cb7ca7"
Parent: "bdb97faf-7f54-4d49-8930-c9f0f8dfb352"
Template: "d227ab0e-fd44-4ae0-878a-189949913d0b"
Path: /sitecore/content/nov/nov/Home/Products and Services/Brands/Chemineer/Applications
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema"
      xmlnxsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{40C0E7ED-9887-49E1-8E89-43D16DD2AD6C}">
        <r
          ds=""
          id="{FA28682B-1CF3-426A-BE1B-F359A64D6282}"
          par="Add Gradient=1&amp;Text Color=white"
          ph="/main/hero-slide-{83C96A38-D18A-4E35-9D8D-71F869B259F3}-0"
          uid="{BA077E75-780B-4654-A220-10E63520C582}" />
        <r
          id="{AB213187-9551-4F9B-AE3D-261BB2B2434F}"
          ph="main"
          uid="{83C96A38-D18A-4E35-9D8D-71F869B259F3}" />
        <r
          ds="{94548DF6-C966-4D24-9F72-80A3038D3133}"
          id="{EAEFE2D3-091C-438E-9B07-903F732D1754}"
          par="Alignment"
          ph="main"
          uid="{C4ACEA35-73C2-4347-B325-2FC6FCDAAB8F}" />
        <r
          ds="{865CE2A2-DF15-40E5-9616-9D69D71DADFB}"
          id="{C9BE8A1C-14D0-4650-BB74-C2797F12C5BA}"
          par=""
          ph="main"
          uid="{E655A92B-3794-4099-AF60-076BAFA33189}" />
        <r
          ds="{2878BC1B-49CD-49D0-996A-4B5AE653C468}"
          id="{7EE99E6C-C671-468E-8381-C6B9BB1E6416}"
          par=""
          ph="main"
          uid="{0D97EC48-A616-4503-81F3-8B0A22142C87}" />
        <r
          ds="{F05D93FB-FAD5-42A9-9B13-14DE5207022F}"
          id="{EAEFE2D3-091C-438E-9B07-903F732D1754}"
          par="Alignment"
          ph="main"
          uid="{1FD9ED8E-765E-4D75-AEB7-9C5643309FB1}" />
        <r
          ds="{7AB952A2-7651-40D9-A6CC-A2ABCE536377}"
          id="{2E6C5F1E-BC4A-4FBE-BC72-FBCB237F8DDC}"
          par=""
          ph="main"
          uid="{C3E128BD-C527-476C-B850-4FF98996AE1F}" />
        <r
          ds="{517887DB-FB1B-44A4-89D5-1150DFDD30C7}"
          id="{F6988CA1-8F6A-4235-8851-39729DDF65B4}"
          par="Alignment=right"
          ph="main"
          uid="{9E4C6427-3865-4F4C-AF91-EFDF6A58DA77}" />
        <r
          ds="{EB445E2D-C2F9-47F3-81DC-F0F9EA8B975F}"
          id="{AE82AE93-5552-4F52-951B-C3A434D646F3}"
          par="Alignment=left&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
          ph="main"
          uid="{ACAD23C8-9219-4D65-B38A-4537A73C4FE0}" />
        <r
          ds="{74BF4C7F-A47B-42AA-A7ED-1C506456BE69}"
          id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
          par="Alignment=right&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
          ph="main"
          uid="{FB4C5C8E-DF5F-4300-950E-536065A8707B}" />
        <r
          ds="{5500BD8B-A72B-40DA-928B-5AC2AB28F48F}"
          id="{417E0128-4AE1-4E78-ACC9-4820C238DD4F}"
          par=""
          ph="main"
          uid="{2849CE03-88F2-4FBC-BAE4-0D1B29D7AEAA}" />
        <r
          ds="{59B4B7A5-2DAB-4C22-B161-B627C26DD527}"
          id="{09A5B06F-A291-4BC8-8851-CC3FBB8D885D}"
          par=""
          ph="main"
          uid="{B5407315-4598-49BA-A716-8895E8E1539E}" />
        <r
          ds="{C5A9D939-B731-4DC7-A048-96B9DB89BA8F}"
          id="{846AE873-D5C7-4033-928F-6BD96E963742}"
          par=""
          ph="main"
          uid="{35F5B041-CCEA-40B8-948D-6DE09851A28E}" />
        <r
          ds="{24EF833C-BB42-42C8-BCB8-299AB69023C0}"
          id="{EAEFE2D3-091C-438E-9B07-903F732D1754}"
          par="Alignment"
          ph="main"
          uid="{99B4E79C-EEB8-49BC-8779-24C4AD0CF113}" />
        <r
          ds="{99A52FBB-AEE5-462B-93E9-42648F5E0588}"
          id="{404FE8DE-C601-4E14-8D3D-32F27B41D06D}"
          par=""
          ph="main"
          uid="{CDF8E396-F69A-48ED-A6DB-B665BD98B242}" />
        <r
          ds="{D5EC64F5-E90A-44BE-92E3-BFDFE13FE68A}"
          id="{1012A5A3-5822-4A4F-9B1B-EB13EB6266EE}"
          par=""
          ph="main"
          uid="{3ADDDF2A-6C4B-4473-ACB2-EADC8ABD6475}" />
        <r
          ds="{BF5F6030-AB5B-4B33-BE76-CAA8C856E00B}"
          id="{8811D96E-0023-4E45-BF2A-E9827DB7E4BB}"
          par=""
          ph="main"
          uid="{8036035A-E577-44BC-A961-631ADBC08C0F}" />
      </d>
    </r>
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{63395D54-AE9C-4C66-B089-EE614DD3A630}"
              p:before="*"
              s:ds="{94548DF6-C966-4D24-9F72-80A3038D3133}"
              s:id="{EAEFE2D3-091C-438E-9B07-903F732D1754}"
              s:par="Alignment=left"
              s:ph="/main/sidebar-content" />
            <r
              uid="{C4ACEA35-73C2-4347-B325-2FC6FCDAAB8F}">
              <p:d />
            </r>
            <r
              uid="{E655A92B-3794-4099-AF60-076BAFA33189}">
              <p:d />
            </r>
            <r
              uid="{0D97EC48-A616-4503-81F3-8B0A22142C87}">
              <p:d />
            </r>
            <r
              uid="{1FD9ED8E-765E-4D75-AEB7-9C5643309FB1}">
              <p:d />
            </r>
            <r
              uid="{C3E128BD-C527-476C-B850-4FF98996AE1F}">
              <p:d />
            </r>
            <r
              uid="{9E4C6427-3865-4F4C-AF91-EFDF6A58DA77}">
              <p:d />
            </r>
            <r
              uid="{ACAD23C8-9219-4D65-B38A-4537A73C4FE0}">
              <p:d />
            </r>
            <r
              uid="{FB4C5C8E-DF5F-4300-950E-536065A8707B}">
              <p:d />
            </r>
            <r
              uid="{2849CE03-88F2-4FBC-BAE4-0D1B29D7AEAA}">
              <p:d />
            </r>
            <r
              uid="{B5407315-4598-49BA-A716-8895E8E1539E}">
              <p:d />
            </r>
            <r
              uid="{35F5B041-CCEA-40B8-948D-6DE09851A28E}">
              <p:d />
            </r>
            <r
              uid="{99B4E79C-EEB8-49BC-8779-24C4AD0CF113}">
              <p:d />
            </r>
            <r
              uid="{CDF8E396-F69A-48ED-A6DB-B665BD98B242}">
              <p:d />
            </r>
            <r
              uid="{49B2F90E-6305-4C40-94A9-3819D82CA563}"
              p:after="r[@uid='{83C96A38-D18A-4E35-9D8D-71F869B259F3}']"
              s:ds="{08A5CC5C-5B36-48C7-96E6-0052561683AA}"
              s:id="{A22722F6-65DF-4574-B659-191957028C9B}"
              s:ph="main" />
            <r
              uid="{A01C10A2-0B0B-4F21-807D-67A6831B0651}"
              p:after="r[@uid='{49B2F90E-6305-4C40-94A9-3819D82CA563}']"
              s:ds="{7760E156-53BD-45E6-8877-537595D5524E}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=right&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{A1B63D24-A734-4CD6-A6D8-56B63282C6C3}"
              p:after="r[@uid='{A01C10A2-0B0B-4F21-807D-67A6831B0651}']"
              s:ds="{219F26A2-0080-40C9-8FA2-59A657D0C5BB}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=left&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{CA866706-3672-4C3F-BA28-5584AF183ECA}"
              p:after="r[@uid='{A1B63D24-A734-4CD6-A6D8-56B63282C6C3}']"
              s:ds="{4E1F2F2B-4D17-44F1-BC57-8FADCD52C733}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=right&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{398A8E48-4400-415A-8006-80CDCF90800B}"
              p:after="r[@uid='{CA866706-3672-4C3F-BA28-5584AF183ECA}']"
              s:ds="{34A1D8C6-EC6F-4EC0-AE77-2D0A448CBFB0}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=left&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{18E42F1C-8317-486E-98DA-B9F071CA2266}"
              p:after="r[@uid='{398A8E48-4400-415A-8006-80CDCF90800B}']"
              s:ds="{9958B1C9-FD0B-43E6-80D6-4443C3AA7C44}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=right&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{2E11324D-9700-42D7-AE73-47CB08D0B0B0}"
              p:after="r[@uid='{18E42F1C-8317-486E-98DA-B9F071CA2266}']"
              s:ds="{F092A602-E312-4C56-A60A-5E43B3A6D4A1}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=left&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{1D2FC24F-6D79-438B-8D1E-BC4DF533CCA0}"
              p:after="r[@uid='{2E11324D-9700-42D7-AE73-47CB08D0B0B0}']"
              s:ds="{E7341A40-9290-4150-880C-8CBC196585A6}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=right&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{459A40B1-D506-4D4A-9E38-BACDB5400396}"
              p:after="r[@uid='{1D2FC24F-6D79-438B-8D1E-BC4DF533CCA0}']"
              s:ds="{D59739C6-C0B4-44E6-8693-08D0A8E79FE4}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=left&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{B4862566-B581-4A68-9E86-4B6630CA6EDF}"
              p:after="r[@uid='{459A40B1-D506-4D4A-9E38-BACDB5400396}']"
              s:ds="{67219647-FBD9-459B-BC3A-B713D564EE27}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=right&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{8A9DAFCC-74DF-4450-B2D4-36C6532AB32B}"
              p:after="r[@uid='{B4862566-B581-4A68-9E86-4B6630CA6EDF}']"
              s:ds="{EBE63786-8B63-4BC5-9143-927DA43A5749}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=left&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{C2BD4B97-DF19-4971-A8DA-97AD9ED6EBA5}"
              p:after="r[@uid='{8A9DAFCC-74DF-4450-B2D4-36C6532AB32B}']"
              s:ds="{2C8E9AD2-06ED-48DA-90CC-673F55F9F78A}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=right&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{2F9B5637-156E-4A96-BC80-B059939B480F}"
              p:after="*[1=2]"
              s:ds="{13EECDB1-9C45-4EAF-B45B-84BDD0F8FACA}"
              s:id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
              s:par="Alignment=left&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
              s:ph="main" />
            <r
              uid="{3ADDDF2A-6C4B-4473-ACB2-EADC8ABD6475}">
              <p:d />
            </r>
            <r
              uid="{8036035A-E577-44BC-A961-631ADBC08C0F}">
              <p:d />
            </r>
          </d>
        </r>
    - ID: "1e6decbd-039c-43cc-b439-0a198f868334"
      Hint: Featured Story Headline
      Value: Chemineer Applications
    - ID: "21d62cf8-1209-47b9-a117-2bb93b891dad"
      Hint: Subheading
      Value: <p>Applications include water &amp; wastewater, flue gas desulfurization, corn wet milling, oil and gas, ethanol, pulp and paper, polymer, chemical, fermentation, mineral processing, general, biotechnology</p>
    - ID: "230a15ec-92fd-4a68-954b-9689bcba0862"
      Hint: Headline
      Value: Chemineer Applications
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210922T185115Z
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: Chemineer Applications
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{40251B7D-FBE3-4A0E-8947-D4B4FE8CD782}"
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: Chemineer Applications
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: Chemineer Applications
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6284a0a8-c973-47ac-af11-eebeffd130b1"
    - ID: "a1343418-5a51-40de-9488-0efaa22e2042"
      Hint: contentTag
      Value: "{97803E00-415E-418E-BD59-EC82DC5F73D8}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "d4ec7ae2-6d57-4ae3-b582-4af2544a7132"
      Hint: Card Image
      Value: |
        <image mediaid="{08EEF214-5907-4A5A-A66B-3D6E2FA7D600}" cropregion="18,0,1901,1080" ratio="514:295" width="514" height="295" />
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210922T195227Z
    - ID: "f758f02c-54af-42b1-bcd8-1b3f90a174be"
      Hint: Page Image
      Value: |
        <image mediaid="{08EEF214-5907-4A5A-A66B-3D6E2FA7D600}" cropregion="0,0,1920,1080" ratio="1920:1080" width="1920" height="1080" />
