---
ID: "13d9a444-0e00-487b-a761-0a0779be3b5d"
Parent: "79269af3-a627-45db-8588-150bb61e8752"
Template: "79269af3-a627-45db-8588-150bb61e8752"
Path: /sitecore/templates/Project/nov/NOV Shared/Field Sections/Cropped Image Fields/Required/Image 385x367 Required/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190121T182401Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9ecb1b84-d2a2-4c5a-a9aa-acf51b8ea0d1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190121T182401Z
