---
ID: "ddf341ba-b5d5-4337-a9ba-fbd061cfa57f"
Parent: "6525cfa5-3afe-4d22-b7d4-e63e21f93e5f"
Template: "569afdf0-3638-43a2-8a58-c569799c1bf7"
Path: /sitecore/content/nov/nov/Data/Modules/Products/CAPS/Intervention and Stimulation Equipment/SSP/Production Tree Shutdown Valves
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: |
        <r owner="sitecore\joannazhu" date="20190918T200218Z" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190918T200218Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\joannazhu
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\joannazhu
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fa1a63c3-d22a-45d5-ada4-02f8ed808e17"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\joannazhu
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190918T200218Z
