---
ID: "e99b9519-1b7b-4c01-bbb0-538665d95596"
Parent: "42c1ae47-4aa6-439d-a6f0-5d35a7ebb789"
Template: "42c1ae47-4aa6-439d-a6f0-5d35a7ebb789"
Path: /sitecore/templates/Project/nov/NOV Shared/Field Sections/Meta Data/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "019c3c8b-3d47-4b92-a8e9-838880ddf307"
      Hint: Open Graph Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120725T134501
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "76c25a5d-166a-4e60-82b2-c88a1ee141da"
      Hint: Open Graph Type
      Value: website
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "358458f1-a5f8-4cce-9586-9e3daf3ecb2d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20130418T200300:635019121805003283"
