---
ID: "c8232fe9-970e-4805-99d6-744462f34474"
Parent: "e6c0ea60-5365-4d76-a05b-b4f05557ad5c"
Template: "f83d9c61-6488-4a85-a988-1338257534e8"
Path: /sitecore/content/nov/nov/Data/Modules/Brand/Chemineer/D7 Authors Block Applications/D7 Author Block Entry General Applications
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210921T160907Z
    - ID: "3daeba35-b5c3-46cb-a587-bd8431066769"
      Hint: jobTitle
      Value: 
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{8B87E652-E3F7-4C54-BDD9-66E1B888FF8B}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "29e85aa2-d254-45a8-9413-1efe5763c223"
    - ID: "95e7dbea-d495-4414-aa9e-4ce9425d16eb"
      Hint: authorName
      Value: General Applications
    - ID: "ae98adc0-112a-4fd9-9103-1075d3bb9555"
      Hint: bio
      Value: |
        <p>Chemineer and Prochem rotating agitators, Greerco High Shear Mixers, and Kenics Static Mixers and Heat Exchangers are
        used in a wide variety of applications and industries.  The ChemScale is used for design purposes based on the
        problem classification of Blending and Motion, Solids Suspension, or Gas Dispersion.</p>
        <h3>Additional applications for mixers and agitators include:</h3>
        <ul>
            <li>Food</li>
            <li>Hazardous Waste</li>
            <li>Paints and Coatings</li>
            <li>Adhesives</li>
            <li>Soy Bean Oil</li>
            <li>Hydrogenators</li>
            <li>Soaps and Detergents</li>
            <li>Cosmetics</li>
        </ul>
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210921T160932Z
