---
ID: "505634ce-2fed-4c6b-8370-d3eadefe1f43"
Parent: "79cb20de-08f9-49b8-9908-1a59dba31aa1"
Template: "79cb20de-08f9-49b8-9908-1a59dba31aa1"
Path: /sitecore/templates/Project/nov/NOV Shared/Modules/Anchor/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170505T152659Z
    - ID: "4bf704a4-80df-4a4b-b3a3-8d09d928f286"
      Hint: Anchor Name
      Value: "-"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "253c8174-2fe0-4a10-93b8-03c96eb84370"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170505T154219Z
