---
ID: "cf221d73-a69a-4b5b-9135-ed6c8698ff22"
Parent: "2ae051a2-af92-4426-8cce-aedaa75d13f9"
Template: "2ae051a2-af92-4426-8cce-aedaa75d13f9"
Path: /sitecore/templates/Project/nov/NOV Shared/Field Sections/Social/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180930T163710Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fc018c94-0f26-43e8-ae2a-9d0e29bef711"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180930T163710Z
