---
ID: "f3c4d9e0-a99a-4601-9abf-33e096f5f382"
Parent: "204acdac-b1b4-4d2e-9631-8a36dea434a7"
Template: "204acdac-b1b4-4d2e-9631-8a36dea434a7"
Path: /sitecore/templates/Feature/NOV Shared/Components/Tab Title/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170306T232017Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e49bebaf-a492-4e7f-958d-3dcdd4d9dd7c"
    - ID: "8e3a4ec9-ef0f-49e1-a014-ab3b6e8222b7"
      Hint: title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170307T003354Z
