---
ID: "06821ee5-22f8-4dbd-82ec-e7ee87a7eb8d"
Parent: "5b27436c-a823-4a17-9a33-b08cbabc9cf5"
Template: "c0aa2bad-85b9-47e4-a236-901c3115fb87"
Path: /sitecore/content/nov/nov/Data/Modules/Products/CAPS/Process and Flow Technologies/Environmental Services/Environmental Services J5 Features List
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200918T181354Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{40251B7D-FBE3-4A0E-8947-D4B4FE8CD782}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2b1899f9-83db-4a69-acb2-3b0180c904a0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "c3afee16-1dbc-4a49-8037-9d03d0d7d62e"
      Hint: description
      Value: |
        <p>In the specialized field of chemical registration, we offer a complete support package from pre-test review of data and chemical components to completion and submission of documentation.</p>
        <p>We work in partnership with the offshore chemical industry with a focus in the North East Atlantic. Our expertise in Harmonised Mandatory Control System (HMCS) supports and guides you through all aspects of Harmonised Offshore Chemical Notification Format (HOCNF) registration and Chemical Hazard Assessment and Risk Management (CHARM) assessments to authorize offshore chemical use.</p>
        <p>HOCNF is used by all the OSPAR North Sea countries, and with our understanding of the unique requirements of the UK, Norwegian, Dutch and Danish regulatory authorities, we can guide you through the complete process.</p>
        <p>Our commitment to a quality service and our long-standing industry experience makes us a trustworthy source to deliver independent environmental consultancy and testing services.</p>
        <p>You may recognize our environmental services from our previous parent companies.&nbsp;In 2013, Opus was acquired by Fjords Processing (Aker Process Solutions at the time) and in 2016, Fjords Processing was acquired by NOV. Please contact our team of experts with questions at any time.</p>
        <h2>Ecotoxicology Testing</h2>
        <p>The ecotoxicology portfolio offers a comprehensive range of marine and freshwater acute and chronic toxicity tests, bioaccumulation and biodegradation studies, which assess environmental risk of chemicals and waste water discharges. This can be performed as Whole Effluent Toxicity (WET) testing or as an individual chemical component to determine the specific chemical toxicity profile. Our tests operate at 3 trophic levels.</p>
        <p>All testing is conducted to the principles of Good Laboratory Practice (GLP) and ISO 9001 accreditation. We pride ourselves on rigorous quality control, assuring you our results are trust-worthy and reliable. Our portfolio of tests follow standardized protocols according to OSPAR, OECD, ISO, ASTM.</p>
        <p>We uniquely culture our own algae, crustaceans and fish stocks, ensuring we always have a constant supply of healthy organisms. Our water system incoming from a local site, Scapa Flow, undergoes a stringent treatment process. Therefore, we have a continual supply of clean water which creates optimal conditions to conduct tests.</p>
        <h2>Environmental Consultancy</h2>
        <p>We have unique expertise in oil industry chemistry, ecotoxicology, environmental dispersion modelling, waste management, risk assessments, legislation and engineering technologies to provide a tailored, exclusive offering to your environmental requirements.</p>
        <p>Our facilities can be used to assess the performance of different chemical packages, separator efficiency and the environmental effects of engineering modifications before these changes are implemented offshore.</p>
        <p>Companies are required to provide evidence to the Department for Business, Energy &amp; Industrial Strategy (BEIS) that they operate to standards defined by Best Available Techniques (BAT) and Best Environmental Practice (BEP) principles, to support Offshore Pollution &amp; Prevention Control (OPPC) permit applications.</p>
        <p>Our methodology ensures you gain the full benefit of utilizing BAT/BEP principles for produced water management to help operators achieve optimal environmental performance with maximum efficiency and enhanced production.</p>
        <p>We are unique in our ability to provide the tools and expertise to deliver the whole BAT/BEP solution by providing a comprehensive resource that considers the entire system. With the intimate relationship between primary separation, produced water and environmental compliance, we offer a highly specialized service.</p>
        <h3>Assessment of environmental risk</h3>
        <h4>Dose-related Risk and Effect Assessment Model (DREAM)</h4>
        <p>Dispersion modelling to determine the Environmental Impact Factor (EIF) of the following:</p>
        <ul>
            <li>Produced water discharges</li>
            <li>Drill cuttings and mud discharges</li>
            <li>MEG discharges</li>
            <li>Discharges to sea from land terminals</li>
            <li>Decommissioning sludge and other residues</li>
        </ul>
        <p>Our expertise in engineering combined with chemistry, ecotoxicology and our knowledge of project management, impact assessment, environmental regulation and hazardous waste make us an ideal partner for assessing environmental risk.</p>
        <p>Management of produced water discharges, extensively used in the UK and Norway for the Risk Based Approach (RBA).</p>
        <p>Identification of substances which contribute the greatest potential harm and also allows the benefits of any mitigating measures to also be quantified.</p>
        <h4>Risk Based Approach (RBA)</h4>
        <ul>
            <li>We can cost-effectively fulfill your total UK RBA obligations through our comprehensive expertise and unique experience in helping the UK Department for Business, Energy &amp; Industrial Strategy (BEIS) develop this leading approach with the RBA trial in 2010.</li>
            <li>Our world-class team of marine ecotoxicologists, chemists and process engineers undertake and manage the toxicity testing, environmental modelling and recommendations based on BAT/BEP principles.</li>
            <li>We can conduct all aspects of the RBA assessment to give a detailed environment risk potential, as well as offer a solution of environmental efficiencies, helping installations come streamlined with the regulatory requirements.</li>
        </ul>
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20201020T163012Z
  - Version: 2
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201103T141918Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{40251B7D-FBE3-4A0E-8947-D4B4FE8CD782}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bb8ce3aa-501f-47e5-971c-c09145cc6af1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "c3afee16-1dbc-4a49-8037-9d03d0d7d62e"
      Hint: description
      Value: |
        <p>In the specialized field of chemical registration, we offer a complete support package from pre-test review of data and chemical components to completion and submission of documentation.</p>
        <p>We work in partnership with the offshore chemical industry with a focus in the North East Atlantic. Our expertise in Harmonised Mandatory Control System (HMCS) supports and guides you through all aspects of Harmonised Offshore Chemical Notification Format (HOCNF) registration and Chemical Hazard Assessment and Risk Management (CHARM) assessments to authorize offshore chemical use.</p>
        <p>HOCNF is used by all the OSPAR North Sea countries, and with our understanding of the unique requirements of the UK, Norwegian, Dutch and Danish regulatory authorities, we can guide you through the complete process.</p>
        <p>Our commitment to a quality service and our long-standing industry experience makes us a trustworthy source to deliver independent environmental consultancy and testing services.</p>
        <p>You may recognize our environmental services from our previous parent companies.&nbsp;In 2013, Opus was acquired by Fjords Processing (Aker Process Solutions at the time) and in 2016, Fjords Processing was acquired by NOV. Please contact our team of experts with questions at any time.</p>
        <h2>Ecotoxicology Testing</h2>
        <p>The ecotoxicology portfolio offers a comprehensive range of marine and freshwater acute and chronic toxicity tests, bioaccumulation and biodegradation studies, which assess environmental risk of chemicals and waste water discharges. This can be performed as Whole Effluent Toxicity (WET) testing or as an individual chemical component to determine the specific chemical toxicity profile. Our tests operate at 3 trophic levels.</p>
        <p>All testing is conducted to the principles of Good Laboratory Practice (GLP) and ISO 9001 accreditation. We pride ourselves on rigorous quality control, assuring you our results are trust-worthy and reliable. Our portfolio of tests follow standardized protocols according to OSPAR, OECD, ISO, ASTM.</p>
        <p>We uniquely culture our own algae, crustaceans and fish stocks, ensuring we always have a constant supply of healthy organisms. Our water system incoming from a local site, Scapa Flow, undergoes a stringent treatment process. Therefore, we have a continual supply of clean water which creates optimal conditions to conduct tests.</p>
        <h2>Environmental Consultancy</h2>
        <p>We have unique expertise in oil industry chemistry, ecotoxicology, environmental dispersion modelling, waste management, risk assessments, legislation and engineering technologies to provide a tailored, exclusive offering to your environmental requirements.</p>
        <p>Our facilities can be used to assess the performance of different chemical packages, separator efficiency and the environmental effects of engineering modifications before these changes are implemented offshore.</p>
        <p>Companies are required to provide evidence to the Department for Business, Energy &amp; Industrial Strategy (BEIS) that they operate to standards defined by Best Available Techniques (BAT) and Best Environmental Practice (BEP) principles, to support Offshore Pollution &amp; Prevention Control (OPPC) permit applications.</p>
        <p>Our methodology ensures you gain the full benefit of utilizing BAT/BEP principles for produced water management to help operators achieve optimal environmental performance with maximum efficiency and enhanced production.</p>
        <p>We are unique in our ability to provide the tools and expertise to deliver the whole BAT/BEP solution by providing a comprehensive resource that considers the entire system. With the intimate relationship between primary separation, produced water and environmental compliance, we offer a highly specialized service.</p>
        <h3>Assessment of environmental risk</h3>
        <h4>Environmental Modelling</h4>
        <p>Dispersion modelling to determine the Environmental Impact Factor (EIF) of the following:</p>
        <ul>
            <li>Produced water discharges</li>
            <li>Drill cuttings and mud discharges</li>
            <li>MEG discharges</li>
            <li>Discharges to sea from land terminals</li>
            <li>Decommissioning sludge and other residues</li>
        </ul>
        <p>Our expertise in engineering combined with chemistry, ecotoxicology and our knowledge of project management, impact assessment, environmental regulation and hazardous waste make us an ideal partner for assessing environmental risk.</p>
        <p>Management of produced water discharges, extensively used in the UK and Norway for the Risk Based Approach (RBA).</p>
        <p>Identification of substances which contribute the greatest potential harm and also allows the benefits of any mitigating measures to also be quantified.</p>
        <h4>Risk Based Approach (RBA)</h4>
        <p>We can cost-effectively fulfill your total UK RBA obligations through our comprehensive expertise and unique experience in helping the UK Department for Business, Energy &amp; Industrial Strategy (BEIS) develop this leading approach with the RBA trial in 2010.</p>
        <p>Our world-class team of marine ecotoxicologists, chemists and process engineers undertake and manage the toxicity testing, environmental modelling and recommendations based on BAT/BEP principles.</p>
        <p>We can conduct all aspects of the RBA assessment to give a detailed environment risk potential, as well as offer a solution of environmental efficiencies, helping installations come streamlined with the regulatory requirements.</p>
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20201103T141918Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20201103T142148Z
