---
ID: "25afccfb-8ea6-43e9-916d-fa9f44eb0232"
Parent: "6bc7494a-672d-49f4-9a8e-9d96f072ff48"
Template: "6bc7494a-672d-49f4-9a8e-9d96f072ff48"
Path: /sitecore/templates/Project/nov/NOV Com/Modules/Forms/Eloqua Form Base/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190108T002120Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "29de5943-895c-441d-a452-b3ac3283b772"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190108T002120Z
