---
ID: "fbc94636-2b55-45b4-a72c-f0ee65586ed4"
Parent: "ddb0aa24-0517-49dc-8c54-9fb2c721446a"
Template: "ddb0aa24-0517-49dc-8c54-9fb2c721446a"
Path: /sitecore/templates/Feature/NOV Shared/Field Sections/Error Pages Content/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1b0c7fed-84f7-40d7-ba24-98966d70c410"
      Hint: Not Found Text
      Value: We're sorry but the page that you're looking for does not exist.
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130222T124451
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jbunch
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jbunch
    - ID: "70260551-8a06-46f3-9ed5-2d74d7e820b1"
      Hint: Access Denied Headline
      Value: Access denied
    - ID: "805dbdfe-bb77-46b3-81e1-1a60d88b77cf"
      Hint: Server Error Headline
      Value: Internal server error
    - ID: "876deee2-ba15-4bf2-bede-86d32ce0fd56"
      Hint: Not Found Headline
      Value: Page not found
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a7b23e11-470e-42da-b495-5a3a53c1eaa0"
    - ID: "957e3318-f814-4a9e-b1f4-7a3c302f0bd3"
      Hint: Access Denied Text
      Value: We're sorry but you do not have access to this part of the site.
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jbunch
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20130222T124616:634971339764670493"
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170323T211437Z
    - ID: "4cf2051e-c9bc-48df-ab81-a51da7945e7a"
      Hint: Page Gone Headline
      Value: Page Gone
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e24c9321-f204-409e-b779-720514f6d38a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170814T164702Z
