---
ID: "2424988f-19a0-4846-8380-e118f73c9031"
Parent: "28957a18-084b-4d4a-8e5a-106ef5677283"
Template: "035f0fcd-adda-4ce6-a3f6-5467a65ab544"
Path: /sitecore/content/nov/nov/Data/Modules/About/News/NOVs Chainsaw cutter configuration enables drilling performance improvements in the Permian/NOVs Chainsaw cutter configuration_D10 Article Subhead
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190621T153327Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\joannazhu
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\joannazhu
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f07a6bd1-4381-43ec-8ed4-078ab6bfd239"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\joannazhu
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190621T154247Z
    - ID: "e7321868-d6dc-4955-b788-53ee24cc95ee"
      Hint: subheadText
      Value: <p>As the market has changed, an area of rapid evolution has been in drill bit cutter design. Cutter design and placement are critical performance enablers that unlock the potential of bits drilling in difficult applications, helping drive up ROP and reduce NPT for customers seeking substantial efficiency gains. The innovative new Chainsaw&trade; cutter configuration unites our ION&trade; 3D cutters with full round cutters on the Tektonic&trade; drill bit to provide the shearing and fracturing cutting actions necessary to cut through shale and interbedded formations. Additionally, the cutters' polished surface reduces cuttings friction at the cutter face.</p>
  - Version: 2
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190621T193305Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\joannazhu
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\joannazhu
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7f3d4625-e115-4d8a-9289-8c51448b9bd8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\joannazhu
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20190621T193305Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190621T193335Z
    - ID: "e7321868-d6dc-4955-b788-53ee24cc95ee"
      Hint: subheadText
      Value: <p>As the market has changed, an area of rapid evolution has been in drill bit cutter design. Cutter design and placement are critical performance enablers that unlock the potential of bits drilling in difficult applications, helping drive up ROP and reduce NPT for customers seeking substantial efficiency gains.</p>
  - Version: 3
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190701T161342Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "5064d9a2-e987-4183-a9cb-d3da7e4c88e0"
      Hint: showDate
      Value: 1
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\joannazhu
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\melissapastrano
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "38642432-f5bc-43a5-9a41-a619c1f2ca1c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20190701T161342Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190702T160124Z
    - ID: "e7321868-d6dc-4955-b788-53ee24cc95ee"
      Hint: subheadText
      Value: <p>As the market has changed, an area of rapid evolution has been in drill bit cutter design. Cutter design and placement are critical performance enablers that unlock the potential of bits drilling in difficult applications, helping drive up ROP and reduce NPT for customers seeking substantial efficiency gains.</p>
