---
ID: "e2c62868-af00-4ef3-8fa9-646a7095bffe"
Parent: "dcab3449-f745-4122-84c4-441399c0ef47"
Template: "dcab3449-f745-4122-84c4-441399c0ef47"
Path: /sitecore/templates/Project/nov/NOV Shared/Rendering Parameters/Product Hero Slider Options/__Standard Values
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190313T135015Z
    - ID: "33de99c1-46ed-4071-a825-dadf8666d2f2"
      Hint: Display Mode
      Value: full size
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fca206da-53c3-458e-a368-033d16689025"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190523T150219Z
