---
ID: "3ec67310-c7e0-4600-8d37-1f0408927bdc"
Parent: "10de6c8e-6a1f-4862-954e-9d7e4c02ac44"
Template: "10de6c8e-6a1f-4862-954e-9d7e4c02ac44"
Path: /sitecore/templates/Feature/NOV Shared/Components/General Link/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170316T203048Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "24d7203f-5b26-49af-908f-98938fc1d6de"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170316T203048Z
