---
ID: "dd5bbbbc-f413-4aba-bc47-9a685b837375"
Parent: "eb339bef-d812-43bd-a0ef-5dff942e51ec"
Template: "eb339bef-d812-43bd-a0ef-5dff942e51ec"
Path: /sitecore/templates/Project/nov/NOV Com/Modules/Map/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "16cf2250-7ef6-44f4-8442-ce2f9789d8c6"
      Hint: Locations
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190214T193816Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "24e31ca1-34c6-412d-b926-69a3bad8f991"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190227T110625Z
