const iconDefaultClassName = '  text-md text-black ';
const iconList = [
  'icon-play',
  'icon-play-outline',
  'icon-pause-outline',
  'icon-pause',
  'icon-facebook',
  'icon-instagram',
  'icon-linked-in',
  'icon-twitter',
  'icon-youtube',
  'icon-resources',
  'icon-description',
  'icon-ruler',
  'icon-chevron-down',
  'icon-chevron-left',
  'icon-chevron-right',
  'icon-chevron-up',
  'icon-download',
  'icon-mail',
  'icon-plus',
  'icon-minus',
  'icon-quote-mark',
  'icon-share-2',
  'icon-check',
  'icon-square',
  'icon-checked-box',
  'icon-search',
  'icon-user',
  'icon-user-check',
  'icon-burger',
  'icon-x',
  'icon-arrow-down',
  'icon-arrow-left',
  'icon-arrow-right',
  'icon-arrow-up',
  'icon-external-link',
  'icon-down-chevron',
];

export { iconDefaultClassName, iconList };
