---
ID: "24a91de1-106e-4f64-aeab-a52016ae33c7"
Parent: "c514004e-6f2f-4108-bc06-c27c6d55fe31"
Template: "035f0fcd-adda-4ce6-a3f6-5467a65ab544"
Path: /sitecore/content/nov/nov/Data/Modules/About/News/Phoenix Series Drill Bits for Geothermal Drilling Applications/Phoenix Series Drill Bits for Geothermal Drilling Applications D10 Article Subhead
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200810T214344Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "90ddc350-b804-46cd-b58e-512b0762437e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jeremygrzywa
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200819T142916Z
    - ID: "e7321868-d6dc-4955-b788-53ee24cc95ee"
      Hint: subheadText
      Value: "<p>Geothermal energy is one of the cleanest and most plentiful energy resources, and a key challenge in geothermal drilling applications is the selection of drill bit solutions. The primary performance objective in a geothermal operation is to successfully drill to a planned subsurface depth at the lowest possible cost per foot drilled. High levels of formation hardness and abrasiveness are the hallmark of igneous and volcanic rocks that are typically encountered in geothermal wells. When drilling in hard formations, higher weight-on-bit requirements generate frictional energy, which can lead to cutting element damage and inhibit drill bit performance. Geothermal drilling applications can also experience downhole vibrations, which is another factor that shortens bit life and impacts drilling performance.</p>"
