---
ID: "adff4d7c-98f9-4342-83e6-dad526bb3799"
Parent: "6e8305bd-e08a-4df3-9743-44c7c97a2671"
Template: "12aa643a-e325-4871-8d72-6a40947f538e"
Path: /sitecore/content/nov/nov/Data/Modules/About/Sustainability/Environmental/Environmental D4 Title Block Environmental Stewardship
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "1448f026-9a23-474a-8df4-af591b152850"
      Hint: title
      Value: Environmental Stewardship
    - ID: "20cce792-a928-4cc0-890c-335dbb42ad4f"
      Hint: body
      Value: <p>At NOV, we embrace environmental stewardship through thoughtful procedures and processes designed to mitigate risks and protect the world in which we operate. We provide sophisticated technologies, products, and services that enable our customers and our facilities to operate in a manner that protects our environment while maintaining compliance with local rules and&nbsp;regulations.</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201008T184350Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rainerschuhsler
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rainerschuhsler
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c0389ac0-a9d7-45c0-8a99-9bf276122d3f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rainerschuhsler
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20201112T033127Z
