---
ID: "194eb292-43fa-4a79-9cd7-5d956f8a33a2"
Parent: "ddf341ba-b5d5-4337-a9ba-fbd061cfa57f"
Template: "c0aa2bad-85b9-47e4-a236-901c3115fb87"
Path: /sitecore/content/nov/nov/Data/Modules/Products/CAPS/Intervention and Stimulation Equipment/SSP/Production Tree Shutdown Valves/Production Tree Shutdown Valves_J5 Features List
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{0534B8A3-7D88-4A2D-B2A6-08C7CCCC67AE}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190918T202043Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "4d669ee9-9ff5-4c31-a025-56035d1727a1"
      Hint: column1Headline
      Value: Features/Benefits
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\joannazhu
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\joannazhu
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aee37245-9588-414d-adb3-0a2851b07690"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\joannazhu
    - ID: "c3afee16-1dbc-4a49-8037-9d03d0d7d62e"
      Hint: description
      Value: |
        <p>Our range of complete fail-safe close shutdown valves in either pneumatic or hydraulic styles ensures surface safety during production operations. Using hydraulic or pneumatic power to open and line pressure/spring return force to close, the frac shutdown valves can be supplied with quick exhaust valves to reduce valve closure time.</p>
        <p>During operation of the production tree shutdown valves, pneumatic or hydraulic control pressure enters the cylinder. The extended stem travels downward, indicating the valve is open. The adjustable down-stop stops further downward movement. The gate valve is now fully open. The actuator is designed to maintain the valve (reverse-acting) in the open position with pneumatic or hydraulic pressure in the actuator.</p>
        <p>Loss of control pressure allows line pressure in the valve body and spring force to move the stem and gate into the closed position.</p>
        <p>The extended stem indicates the valve is closed. The metal-to-metal seat between the actuator bonnet and lower stem serves as a secondary seal.</p>
        <p>Upstream valve body pressure helps to isolate line pressure from downstream with less than 100 psi in the valve body.</p>
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200122T165049Z
    - ID: "f6afec27-750a-4d77-962d-3ce002b623b9"
      Hint: column1List
      Value: |
        <ul>
            <li>Ease of maintenance &ndash; The unit can be redressed without special tools or external pressure sources. Piston and upper stem packing is easily removable using actuator service disconnect bolts. Standardized lower stem sizes simplify spare parts requirements.</li>
            <li>Proven reliability &ndash; API 6A, PR2 Appendix F qualified surface safety valve (SSV)</li>
            <li>Large diaphragm area on AUD actuators &ndash; Permits use of a low-pressure air or gas control system. A relief valve on the cylinder acts to protect against damage to the diaphragm in case of excessive pressure increases.</li>
            <li>Visual open/close indication &ndash; Upper stem extension indicates gate position at a glance</li>
            <li>Interchangeable with all other AU models, allowing conversion from hydraulic to pneumatic actuation and vice versa</li>
        </ul>
  - Version: 2
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200609T193835Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{85C553F7-205F-4672-8AD9-95180934AD15}"
    - ID: "4d669ee9-9ff5-4c31-a025-56035d1727a1"
      Hint: column1Headline
      Value: Features/Benefits
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\joannazhu
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kaylakaplan
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "abd9b67d-8042-4268-94a9-5e8accaaccd6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kaylakaplan
    - ID: "c3afee16-1dbc-4a49-8037-9d03d0d7d62e"
      Hint: description
      Value: |
        <p>Our Axelson&trade; range of complete fail-safe close shutdown valves in either pneumatic or hydraulic styles ensures surface safety during production operations. Using hydraulic or pneumatic power to open and line pressure/spring return force to close, the frac shutdown valves can be supplied with quick exhaust valves to reduce valve closure time.</p>
        <p>During operation of the production tree shutdown valves, pneumatic or hydraulic control pressure enters the cylinder. The extended stem travels downward, indicating the valve is open. The adjustable down-stop stops further downward movement. The gate valve is now fully open. The actuator is designed to maintain the valve (reverse-acting) in the open position with pneumatic or hydraulic pressure in the actuator.</p>
        <p>Loss of control pressure allows line pressure in the valve body and spring force to move the stem and gate into the closed position.</p>
        <p>The extended stem indicates the valve is closed. The metal-to-metal seat between the actuator bonnet and lower stem serves as a secondary seal.</p>
        <p>Upstream valve body pressure helps to isolate line pressure from downstream with less than 100 psi in the valve body.</p>
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20200609T193835Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200609T193936Z
    - ID: "f6afec27-750a-4d77-962d-3ce002b623b9"
      Hint: column1List
      Value: |
        <ul>
            <li>Ease of maintenance &ndash; The unit can be redressed without special tools or external pressure sources. Piston and upper stem packing is easily removable using actuator service disconnect bolts. Standardized lower stem sizes simplify spare parts requirements.</li>
            <li>Field-proven Axelson reliability &ndash; API 6A, PR2 Appendix F qualified surface safety valve (SSV)</li>
            <li>Large diaphragm area on AUD actuators &ndash; Permits use of a low-pressure air or gas control system. A relief valve on the cylinder acts to protect against damage to the diaphragm in case of excessive pressure increases.</li>
            <li>Visual open/close indication &ndash; Upper stem extension indicates gate position at a glance</li>
            <li>Interchangeable with all other AU models, allowing conversion from hydraulic to pneumatic actuation and vice versa</li>
        </ul>
